### ISSUE TITLE
skiaSharp 2.80.3 usage

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/BinaryKits.Zpl#101]
> Hi, This nuget package is very helpful. Thank you for creating it. The requirement for this package is to have skiaSharp >= 2.80.3. But there is an issue with this version: https://github.com/mono/SkiaSharp/issues/1860 https://github.com/mono/SkiaSharp/issues/1767
> It works with skiaSharp version 2.80.2. There is any issue with using this version?
>

**Comment by tinohager** [comment]
There should be no problems from my point of view.
