### ISSUE TITLE
Field Number (^FN) and Recall / Download Format (^DF, ^XF)

### ISSUE THREAD

**Issue by MRejou** [BinaryKits/BinaryKits.Zpl#102]
Hello,

For a project I needed to handle ^FN, ^DF and ^XF commands in existing .zpl files (I cannot change those files).

DF : "template" declaration
XF : "template" usage
FN : field declaration and usage
Details here : https://www.servopack.de/support/zebra/ZPLII-Prog.pdf

In order to do that, I had to make a few changes to the lib :
 - Added FieldNumberCommandAnalyzer, DownloadFormatCommandAnalyzer, RecallFormatCommandAnalyzer
 - Added ZplFieldNumber and ZplRecallFormat elements
 - Updated FieldDataZplCommandAnalyzer to return an element matching ^FN...^FD... pair
 - Updated FieldSeparatorZplCommandAnalyzer to return an element matching trailing ^FN commands before ^FS
 - Added DownloadFormatName property in LabelInfo class
 - Added few properties to VirtualPrinter
 - Added format merging in ZplAnalyzer

Can I create a pull request so that those new features are available for everyone ?

**Comment by tinohager** [comment]
Yes of course you can send a pull request. We are happy about additional functionality

**Comment by MRejou** [comment]
Great thanks ! I'm on it

**Comment by MRejou** [comment]
Hello, the pull request is available if you have few time for review (no emergency at all :) )

I tried to match existing coding style

**Comment by tinohager** [comment]
Can you maybe also add some test labels?
https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer.WebApi/Labels/Test

**Comment by MRejou** [comment]
sure, doing that asap

**Comment by MRejou** [comment]
Hello, I pushed an example (and a tiny fix to handle non-trimmed ^XA and ^XZ commands)

**Comment by tinohager** [comment]
I will do it the week

**Comment by MRejou** [comment]
thanks !

**Comment by tinohager** [comment]
new nuget packages now available
