### ISSUE TITLE
Can it be ported to .net framework 4.5?

### ISSUE THREAD

**Issue by Tilation** [BinaryKits/BinaryKits.Zpl#107]
Current supported versions are:
* .Net Framework 4.7.2
* .Net Core 5.0
* .Net Standard 2.0

Can it be ported to .Net Framework 4.5?

Am I allowed to fork and port it so it support older Framework versions?

**Comment by Tilation** [comment]
The reason is that the project I am working on can't be ported to any .Net framework higher than 4.5 for compatibility regards.
As many of the libraries that are being used are dead and there are no modern alternatives or are to big to develop from the ground up.

**Comment by tinohager** [comment]
Running one project separately and communicating via rest with the httpclient not an option?

**Comment by Tilation** [comment]
Absolutely not, the project runs on many many client servers and there is no room to expand the infrastructure and / or change it. I'll try my best to port this.

**Comment by Tilation** [comment]
I ported it to `.Net Framework 4.5`, you can check out the modifications here: https://github.com/Tilation/BinaryKits.Zpl.net45
