### ISSUE TITLE
EAN-13 bar code is not supported in Viewer

### ISSUE THREAD

**Issue by haitao2008** [BinaryKits/BinaryKits.Zpl#109]
I found EAN-13 bar code is not supported in the viewer. So any element started with ^BE will be drawed as a normal label text field not a 2D barcode.
Do you guys have any plan to support this type of barcode in the Viewer? 
Thanks.

**Comment by tinohager** [comment]
At the moment it is not planned.

**Comment by tinohager** [comment]
Thanks for the PR
