### ISSUE TITLE
Viewer convert to PDF instead image

### ISSUE THREAD

**Issue by ingfdoaguirre** [BinaryKits/BinaryKits.Zpl#115]
Hi I recently made some PRs to fix some bugs.

This was the initial viewer result, before fixes:
![first](https://user-images.githubusercontent.com/19358221/172099135-46dabccc-04b7-491b-b602-aaba0e366e1c.png)

**And after fixes this was the result:**
![label0](https://user-images.githubusercontent.com/19358221/172099237-54bc2170-aefc-4f9b-8493-6e2a831f3f09.png)

**This is the result using Labelary:**
![labelary](https://user-images.githubusercontent.com/19358221/172099742-5b69cc18-f8b2-4fc4-a9f9-7f95fc56c471.png)

I can say that is approximately the same result, maybe your viewer needs some tune(in font sizes and types) , but nothing big.

Now that those bugs are fixed, I need want to know if can I create a PDF file instead a image files, I know that I can create a PDF and add 1 image per page, but I saw in Labelary that, when you donwload as PDF file, the resulting file doesnt have images on each PDF page, it have text.

This is an example that proves that if you download PDF from Labelary, all is rendered as text (I select it, to prove it):
![2022-06-05_22-27](https://user-images.githubusercontent.com/19358221/172100426-55621cdd-a145-4388-b49d-478b1e1b89d0.png)

So can I create a PDF instead an image? or do I need to investigate and create my own function?

Thank you!

**Comment by ingfdoaguirre** [comment]
Hi, I have an update.

I'm using pdfSharp to create PDFs based on ElementDrawers from viewer, wit some modifications.

At this moment I had ported this classes to draw in a PDF page, instead a image (I created other classes adding Pdf before Element, like TextField**Pdf**ElementDrawer):
```
TextFieldElementDrawer
QrCodeElementDrawer
FieldBlockElementDrawer
Barcode128ElementDrawer
Barcode39ElementDrawer
BarcodeEAN13ElementDrawer
```
The text highlighted in pink, is text, not an image!

![2022-06-10_17-25](https://user-images.githubusercontent.com/19358221/173165288-507d1a5a-41d6-44bd-a0b8-c6be18e91668.png)

**Comment by YipingRuan** [comment]
@ingfdoaguirre  Thank you!
> Hi I recently made some PRs to fix some bugs.


Just to confirm the PDF support is to allow user download a PDF file, and has nothing to do with the web page rending?

**Comment by gurunathgopireddy** [comment]
Hello @ingfdoaguirre 

Is there any example I can use to create PDF files instead of images?
Thank you

**Comment by avan2s** [comment]
Hello @ingfdoaguirre ,  
pdf conversion is something I am currently missing here. Could you please share the code with us? I think this will help many people out there which need to handle label requirements  :)

Thanks a lot and best regards
