### ISSUE TITLE
Viewer quality

### ISSUE THREAD

**Issue by zamgill** [BinaryKits/BinaryKits.Zpl#141]
Would like the ability to specify image quality for the `Draw` method of `BinaryKits.Zpl.Viewer.ZplElementDrawer.cs`
https://github.com/BinaryKits/BinaryKits.Zpl/blob/44e1a6ca07f78d6c53d29b7dacc4bf56c6ff5404/src/BinaryKits.Zpl.Viewer/ZplElementDrawer.cs#L49-L53

Currently it defaults to **80**:
https://github.com/BinaryKits/BinaryKits.Zpl/blob/44e1a6ca07f78d6c53d29b7dacc4bf56c6ff5404/src/BinaryKits.Zpl.Viewer/ZplElementDrawer.cs#L103-L104

**Comment by primo-ppcg** [comment]
Added both RenderQuality and RenderFormat to [ElementDrawers.DrawerOptions](https://github.com/BinaryKits/BinaryKits.Zpl/blob/master/src/BinaryKits.Zpl.Viewer/ElementDrawers/DrawerOptions.cs#L12).
