### ISSUE TITLE
QR code drawn on incorrect position

### ISSUE THREAD

**Issue by rekonder** [BinaryKits/BinaryKits.Zpl#142]
Hi, 

I am testing the BinaryKits Viewer label image generator. And I found a problem with the QR code drawing. I used the next ZPL code

```
^XA
^FT20,122^BQ,2,3
^FH^FDLA,123456789012^FS
^FT111,52^A0N,23,23^FH^FDTest^FS
^XZ

```
BinaryKits viewer produces the next label: 

![image](https://user-images.githubusercontent.com/7748774/199544129-a6be612d-bcf2-4fad-a9e0-4f2ca879f357.png)

If I use the same ZPL code in the labelary service or try to print on the real label printer I get the next label

![image](https://user-images.githubusercontent.com/7748774/199544557-2d0c60c6-3a1a-4e9a-96f4-a56cc883ce33.png)

Looks like the BinaryKits viewer does not use correctly ^FT command before the ^BQ command. In case I change the ^FT command with ^FO in labelary I get the same image as the BinaryKits viewer.

**Comment by primo-ppcg** [comment]
Thanks for the bug report. You're correct that `^FT` is not being passed to QR Code elements.
