### ISSUE TITLE
ZPL View Korean

### ISSUE THREAD

**Issue by suhoKKK** [BinaryKits/BinaryKits.Zpl#146]
hello. I need to convert ZPL to image and this solution helped me a lot. However, it seems that the problem I am facing is not converting Korean to ZPL. I live in Korea and most of the labels are in Korean. Is Korean not supported in the library? Usually ^SEE:UHANGUL.DAT^FS
^CW1,E:KFONT3.FNT^CI26^FS
^CI28
^CFJ,50 add in front, you can see Korean, but it doesn't seem to work with this library.

**Comment by primo-ppcg** [comment]
This code refers to two files located on your physical printer:

`UHANGUL.DAT` - An ecoding table
`KFONT3.FNT` - A font file which replaces the default font `1`

The first of these cannot be emulated with this library, unfortunately. The second, however can. You can define your own drawer options to replace the default font `1`.

```csharp
IPrinterStorage printerStorage = new PrinterStorage();
DrawerOptions drawerOptions = new DrawerOptions() {
    FontLoader = fontName => {
        if(fontName == "1") {
            return typeface = SKTypeface.FromFile(@"KFONT3.FNT");
        }
        return SKTypeface.Default;
    }
};
var drawer = new ZplElementDrawer(printerStorage, drawerOptions);
```

**Comment by YipingRuan** [comment]
@primo-ppcg 
Great finally we are able to inject some font loading logic.
