### ISSUE TITLE
Not supported ZPL format  " R:TDirect.ZPL  "

### ISSUE THREAD

**Issue by apapanian** [BinaryKits/BinaryKits.Zpl#150]
I am getting an error generating PNG using
BinaryKits.Zpl.Viewer

My ZPL works at   Labelary   [ http://labelary.com/viewer.html ]
On  BinaryKits.Zpl.Viewer.WebApi [ https://binarykits-zpl-viewer.azurewebsites.net/ ]
 and using my code  I am getting the error below
Could not find format R:TDirect.ZPL

**Comment by primo-ppcg** [comment]
Please provide a minimal ZPL sample that recreates the issue.

**Comment by apapanian** [comment]
^FS~TA000~JSN^LT0^MNW^PON^PMN^LH0,0^JMA^MD15^LRN^CI0^MMT^PW812^LL1218^LS0^POI^FT122,408^A0N,42,40^FH\^FN36^FS^FT122,372^A0N,42,40^FH\^FN35^FS^FT122,336^A0N,42,40^FH\^FN4^FS^FT726,51^A0N,28,28^FH\^FN8^FS^FT657,51^A0N,28,28^FH\^FN7^FS^FT420,46^A0N,28,28^FH\^FN9^FS^FT461,47^A0N,28,28^FH\^FN10^FS^BY3,3,187^FT88,980^BCN,,N,N,N,A^FN11^FS^FT180,761^A0N,28,28^FH\^FN37^FS^FT16,718^A0N,56,55^FH\^FN12^FS^FT134,1033^A0N,28,28^FH\^FN20^FS^FT15,1172^A0N,28,28^FH\^FN39^FS^FT15,1137^A0N,28,28^FH\^FN38^FS^FT15,1102^A0N,28,28^FH\^FN16^FS^FT15,1068^A0N,28,28^FH\^FN15^FS^FT357,1033^A0N,28,28^FH\^FN14^FS^FT272,517^A0N,85,84^FH\^FN17^FS^BY3,3,107^FT311,639^BCN,,N,N,N,A^FN18^FS^FT26,32^A0N,23,24^FH\^FN28^FS^FT26,86^A0N,23,24^FH\^FN21^FS^FT26,140^A0N,23,24^FH\^FN25^FS^FT26,167^A0N,23,24^FH\^FN27^FS^FT26,59^A0N,23,24^FH\^FN22^FS^FT26,113^A0N,23,24^FH\^FN23^FS^FT122,203^A0N,28,28^FH\^FN30^FS^FT122,233^A0N,28,28^FH\^FN33^FS^FT122,267^A0N,28,28^FH\^FN29^FS^FT122,301^A0N,28,28^FH\^FN31^FS^FT122,335^A0N,28,28^FH\^FN32^FS^BY0,0^FT15,640^BD^FH\960190000040^FN2^FS^FT645,750^A0N,94,84^FH\^FN34^FS^FT692,1198^A0N,17,16^FH\^FN45^FS^FT592,87^A0N,23,24^FH\^FN40^FS^FT617,112^A0N,23,24^FH\^FN41^FS^FT587,139^A0N,23,24^FH\^FN42^FS^FT646,1048^A0N,45,45^FH\^FN43^FS^FT656,1080^A0N,28,28^FH\^FN44^FS^FT242,1204^A0N,28,28^FH\^FN46^FS^FO1,417^GB811,0,8^FS^FO2,650^GB809,0,8^FS^FO0,768^GB812,0,8^FS^FO0,995^GB811,0,8^FS^FT30,208^A0N,34,38^FH\^FDSHIP^FS^FT30,250^A0N,34,38^FH\^FD TO:^FS^FO243,418^GB0,236,8^FS^FT682,51^A0N,28,28^FH\^FDOF^FS^FT14,760^A0N,28,28^FH\^FDTRACKING #:^FS^FT16,1033^A0N,28,28^FH\^FDBILLING:^FS^FO682,650^GB130,0,118^FS^FT14,1204^A0N,28,28^FH\^FDCM SHIPMENT ID#^FS^XZ^FX[Recall]^FS^XA^XFR:TDirect.ZPL^FN33^FD201-673-7431^FS^FN22^FD512-777-1078^FS^FN3^FD^FS^FN11^FD1Z7Y5F670319782557^FS^FN44^FD^FS^FN23^FDAUSTIN, TX 78702^FS^FN4^FD^FS^FN12^FDUPS GROUND^FS^FN34^FD^FS^FN45^FD15.5A 07/2019^FS^FN46^FD1101052622^FS^FN35^FDHOLMDEL NJ 07733-2781^FS^FN24^FD^FS^FN5^FD^FS^FN13^FD^FS^FN25^FD^FS^FN6^FD^FS^FN14^FD^FS^FN37^FD1Z 7Y5 F67 03 1978 2557^FS^FN26^FD^FS^FN7^FD1^FS^FN15^FD^FS^FN27^FD^FS^FN8^FD1^FS^FN16^FD^FS^FN38^FDRef 01: YDU000009683487^FS^FN28^FDYETI CUSTOM^FS^FN9^FD1^FS^FN17^FD NJ 077 0-06^FS^FN39^FDRef 02: 26936326/107252300^FS^FN29^FD66 BANYAN BLVD^FS^FN18^FD42184007733^FS^FN19^FD^FS^FN40^FD^FS^FN41^FD^FS^FN30^FDSURESH NJ^FS^FN42^FD^FS^FN31^FD^FS^FN20^FDF/D^FS^FN32^FD^FS^FN21^FD3411 HILDAGO STREET^FS^FN2^FH^FD003840077332781[)>_1E01_1D961Z19782557_1DUPSN_1D7Y5F67_1D342_1D_1D1/1_1D1_1DN_1D_1DHOLMDEL_1DNJ_1E_04^FS^FN10^FDLBS^FS^FN43^FDINV-CC^FS^FN47^FD03^FS^PQ1,0,1,Y^XZ^FX End of job

**Comment by apapanian** [comment]
This label  contains UPS maxicode.

**Comment by primo-ppcg** [comment]
> This label contains UPS MaxiCode.

Unrelated to the bug reported. `^BD` is unsupported at this time.
