### ISSUE TITLE
Zpl Barcode Orientation

### ISSUE THREAD

**Issue by heilmanker** [BinaryKits/BinaryKits.Zpl#152]
Barcoes are not orienting correctly in BinaryKits.  The BC orientation tag is not being honored when using the following ZPL:

 ^XA  ^FO 810,20 ^GB 0,1170,5 ^FS  ^FO 745,40 ^A0R,60,40 ^FD Label Title ^FS  ^FO 740,20 ^GB 0,1170,5 ^FS  ^FO 690,40^A0R,40,40 ^FD TAG # ^FS  ^FO 690,150^A0R,40,40 ^FD 100000056 ^FS  ^FO 580,700 ^BY 3 ^BC R,80,N,N,N ^FD 100000056 ^FS  ^XZ

Labelary (and ZPL printers) draw as follows:
![image](https://user-images.githubusercontent.com/28175243/208506904-3e3a836a-0f7e-4fbe-aadb-a7f5e216aa60.png)

BinaryKits draws as follows:
![image](https://user-images.githubusercontent.com/28175243/208507068-e27fc218-0f28-40c8-b79b-29bc92ff201e.png)

Here is the BC documentation from Labelary:

^BC orientation, height, line, lineAbove, checkDigit, mode
Configures the current field as a Code 128 bar code.
Parameters:
orientation: The bar code orientation to use. Valid values are N (no rotation), R (rotate 90° clockwise), I (rotate 180° clockwise), and B (rotate 270° clockwise). The default value is the orientation configured via the ^FW command, which itself defaults to N (no rotation).
height: The bar code height, in dots. Any number between 1 and 32,000 may be used. The default value is the bar code height configured via the ^BY command, which itself defaults to 10.
line: Whether or not to include human-readable text with the bar code. Valid values are Y and N. The default value is Y (include human-readable text).
lineAbove: Whether or not to place the human-readable text above the bar code. Valid values are Y and N. The default value is N (if printed, text is placed below the bar code), except for mode U where the default is Y (if printed, text is placed above the bar code).
checkDigit: Whether or not to calculate a GS1 (UCC) Mod 10 check digit. Valid values are Y and N. The default value is N (GS1 check digit is not calculated).
mode: The mode to use to encode the bar code data. Valid values are N (no mode, subsets are specified explicitly as part of the field data), U (UCC case mode, field data must contain 19 digits), A (automatic mode, the ZPL engine automatically determines the subsets that are used to encode the data), and D (UCC/EAN mode, field data must contain GS1 numbers). The default value is N (no mode, subsets are specified explicitly as part of the field data).
Example (common usage): ^BC,50
Example (full usage): ^BCN,50,Y,N,N,A

**Comment by heilmanker** [comment]
When its parsing commands using ZplCommandAnalyzerBase.SplitCommand the first element in the resultant string[] has a space in it.  So the ConvertFieldOrienation doesn't work because its trying to find  "R" but the value is actually " R".  The fix is to add a trim method to the ZplCommandAnalyzerBase.ConvertFieldOrientation Method.

So go from this:

 protected FieldOrientation ConvertFieldOrientation(string fieldOrientation)
        {
            return fieldOrientation switch
            {
                "N" => FieldOrientation.Normal,
                "R" => FieldOrientation.Rotated90,
                "I" => FieldOrientation.Rotated180,
                "B" => FieldOrientation.Rotated270,
                 _  => FieldOrientation.Normal,
            };
        }

To this:

 protected FieldOrientation ConvertFieldOrientation(string fieldOrientation)
        {
            return fieldOrientation.Trim() switch
            {
                "N" => FieldOrientation.Normal,
                "R" => FieldOrientation.Rotated90,
                "I" => FieldOrientation.Rotated180,
                "B" => FieldOrientation.Rotated270,
                 _  => FieldOrientation.Normal,
            };
        }

**Comment by primo-ppcg** [comment]
Your label markup doesn't adhere to the specification:

```
Format ^BCo,h,f,g,e,m
```
[ZPL II Programming guide, P1012728-009 Rev. A](https://support.zebra.com/cpws/docs/zpl/BC_Command.pdf) (pdf)

Although, if a physical printer interprets this correctly, it should probably be emulated as well. It seems to me, however, that many commands would fail to render properly, if the first parameter is non-numeric. I believe it would a better solution to ignore trailing whitespace after any command, rather than handling each individually.
