### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by gayathrijosyula** [BinaryKits/BinaryKits.Zpl#154]
![image](https://user-images.githubusercontent.com/121975085/211549617-08a1202e-bc66-4e9f-b816-060589d701ea.png)
Getting System.AccessViolationException in Drawer.draw

**Comment by primo-ppcg** [comment]
Please provide a minimal ZPL sample that recreates the issue.

**Comment by gayathrijosyula** [comment]
This ZPL sample can be used 
^XA^FT190,110^A0N,80^FDJohn^FS^FT190,220^A0N,80^FDHU12 8JN^FS^FT190,330^A0N,80^FDFri 02 Dec 2022^FS^FT190,420^A0N,50^FDCastleford, Route 7002^FS^FT190,460^A0N,50^FDorder ref: qwertyuiop345678^FS^FT620,215^A0N,80^FD1 / 1^FS^XZ

**Comment by primo-ppcg** [comment]
I am unable to reproduce. The [online viewer](https://binarykits-zpl-viewer.azurewebsites.net/) has no issue, nor does my local deployment. If the issue is persistent, I would suppose that something is not right with your development environment.

**Comment by MohamedGobran** [comment]
I have faced the same error before, usually it will happen after generating several label previews within short period of time.
When I used the preview to generate preview for  consequent several labels, this error will happen.
