### ISSUE TITLE
DownloadGraphics compression uses two characters for a single repeated character. 

### ISSUE THREAD

**Issue by danzk** [BinaryKits/BinaryKits.Zpl#157]
I noticed that the ZebraHexCompressionHelper.Compress method will use a 'G' for a single repeated character instead of just doing nothing. So you will get gJ0G1G8, when when gJ018, would be more optimal.

**Comment by YipingRuan** [comment]
@tinohager 
Did we have duplicate `ZebraHexCompressionHelper` at both `BinaryKits.Zpl.Label` and `BinaryKits.Zpl.Protocol` ?

**Comment by tinohager** [comment]
@YipingRuan yes this is duplicate. This is what has happened historically. I did not want to add any additional dependencies. Basically, the protocol should become the basis for everything.

**Comment by primo-ppcg** [comment]
Resolved in #169.
