### ISSUE TITLE
 Arabic text is not rendered 

### ISSUE THREAD

**Issue by MohamedGobran** [BinaryKits/BinaryKits.Zpl#162]
Arabic text is not rendered correctly, as shown in attached screen shot of binarykits viewer. the arabic letters are written separated and reversed.
![BinaryKits Arabic text](https://github.com/BinaryKits/BinaryKits.Zpl/assets/78532267/76c5930d-7d0c-4f85-b6b7-c375f697bfc7)

**Comment by primo-ppcg** [comment]
It appears that SkiaSharp's `DrawText` does not support RTL fonts. One must instead use `DrawShapedText`, which requires an additional dependency, albeit a small one.

Before:
![before](https://github.com/BinaryKits/BinaryKits.Zpl/assets/4907320/3efdba8e-a26e-40f4-9a43-bbf14164c787)

After:
![after](https://github.com/BinaryKits/BinaryKits.Zpl/assets/4907320/01415d83-8a50-40d1-8ddb-8ff7536ae893)
