### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by MohamedGobran** [BinaryKits/BinaryKits.Zpl#170]
![BinaryKits Exception ](https://github.com/BinaryKits/BinaryKits.Zpl/assets/78532267/9858f88e-63a7-40ab-ad6a-8b60aea6fcf4)

> Exception==>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetFontHeight(HandleRef font, HandleRef graphics, Single& size)
   at System.Drawing.Font.GetHeight(Graphics graphics)
   at System.Drawing.Font.GetHeight()
   at System.Drawing.Font.get_Height()
   at BarcodeLib.Barcode.Generate_Image()
   at BarcodeLib.Barcode.Encode()
   at BinaryKits.Zpl.Viewer.ElementDrawers.Barcode128ElementDrawer.Draw(ZplElementBase element, DrawerOptions options)
   at BinaryKits.Zpl.Viewer.ZplElementDrawer.Draw(ZplElementBase[] elements, Double labelWidth, Double labelHeight, Int32 printDensityDpmm)
   at PreviewGenerator.Preview.LabelPreviewFactory.VirualPrinterPreview(String labelZpl, Double scaleFactor) 

this is the code we use
![BinaryKits code](https://github.com/BinaryKits/BinaryKits.Zpl/assets/78532267/c67a9e54-3203-4ffa-a344-874dfb584c18)

we are sometimes getting this Exception , and it leads to the application crashing. 
all exceptions are happening at Barcode128ElementDrawer.
I am using the analyzer.Analyze two times [the exception is not happening every time even with the same ZPL] it is happening arbitrarily  , the first one to download the graphics which will be called on the label, the second time is for processing the label.
I tried to combine the graphics download with label but it was sometimes also raising the same exception.

also please note we are downloading 29 images using the download graphics, these images it will stay in the virtual printer storage, and each label will contain at maximum 3 images only.

I noticed that there were a similar issue raised before with exception similar to this one but it is closed and still the issue is present.
this is the previously raised issue #154
your support is much appreciated.

**Comment by primo-ppcg** [comment]
Perhaps related: #145 

Related, in that the exception is raised through BarcodeLib. The [latest release](https://github.com/barnhill/barcodelib/pull/152) no longer relies on `System.Drawing`, which should solve both issues.

**Comment by MohamedGobran** [comment]
But BinaryKits.Zpl.Viewer still using the old BarcodeLib version 2.4.0 and when I update to the latest version 3.0.0 BinaryKits.Zpl.Viewer failed to build with lots of errors.
![Depricated BarcodeLib](https://github.com/BinaryKits/BinaryKits.Zpl/assets/78532267/8b25e2c4-1870-4f7f-86c6-bf7a8b73202a)

after update to BarcodeLib Version 3.0.0 and try to build these build error will appear.
![update BarcodeLib](https://github.com/BinaryKits/BinaryKits.Zpl/assets/78532267/0153470f-f6ff-4a8b-ba8f-d74e81d3db93)

**Comment by primo-ppcg** [comment]
> But BinaryKits.Zpl.Viewer still using the old BarcodeLib version 2.4.0 and when I update to the latest version 3.0.0 BinaryKits.Zpl.Viewer failed to build with lots of errors.

Yes, that's right. The 2.x branch is not compatible with the 3.0 branch. Significant modifications will need to be made. I intend to do this on the weekend.

**Comment by primo-ppcg** [comment]
The maintainer appears to have removed the `LabelPosition` property from the `Barcode` class. Given this library has a number of other limitations, it may be easiest to drop the dependency, and rely on ZXing for the encoding.
