### ISSUE TITLE
Text distortion

### ISSUE THREAD

**Issue by yelhouti** [BinaryKits/BinaryKits.Zpl#180]
Thanks for the great work, I found the project today and started playing with it. I added support for cors (PR pending).
But once I started adding some real life exemple I found the text too distorted.
As far as I can tell zebra printers do not distort texts. any idea what might be causing this.
ex:
```
^XA
^FO8,8^A0,,32,^FD{name}^FS
^FO8,44^BC,80,,,,A^FD{barcode}^FS
^FO8,200^A0,,120,^FD{priceInclTax}^FS
^XZ
```
57, 43, 8
And compare with overlay/labelery.
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/5471639/af2d3915-f009-4cd7-b6a8-01d3a293a22b)

**Comment by primo-ppcg** [comment]
You're correct. The text is not scaled uniformly if only one dimension is given. As work-around, you can provide the same value for both width and height:
```zpl
^A0,32,32,
```

**Comment by yelhouti** [comment]
@primo-ppcg thanks for the workaround, I think it should be easy fix though.
