### ISSUE TITLE
^CI causes error

### ISSUE THREAD

**Issue by yelhouti** [BinaryKits/BinaryKits.Zpl#183]
This is a very common command to accept accents..., it would be great if we could use it with all chartsets

**Comment by primo-ppcg** [comment]
While `^CI` is not supported, it shouldn't actually cause an error. The code page is implicitly UTF-8 (`^CI28`). Emulating other code pages could theoretically be done - with much effort - by using translation tables.

**Comment by yelhouti** [comment]
@primo-ppcg while ^CI28 is default in the library it is not on the printer.
I am not advocating for implementing the others, just to not return/show an error when the command is used.
