### ISSUE TITLE
Fonts not matching what is printed

### ISSUE THREAD

**Issue by yelhouti** [BinaryKits/BinaryKits.Zpl#184]
I guess there is a good reason why this program doesn't already include all the zebra fonts.
Is there a way to add them and work with them so that the preview exactly matches the printed label.

**Comment by primo-ppcg** [comment]
Zebra fonts are proprietary, and cannot be distributed freely. I you would like to the preview to match exactly, it would be best to extract the "Swiss 721 BT" from a printer, and use that in your DrawerOptions.

Other fonts with similar metrics include Helvetica SemiCondensed (Narrow) Bold, and CG Triumvirate Condensed Bold.

**Comment by yelhouti** [comment]
@primo-ppcg how is it the case that [labelary](http://labelary.com/viewer.html) is able to use them ?
I am in contact with zebra trying to solve this.

**Comment by primo-ppcg** [comment]
> @primo-ppcg how is it the case that [labelary](http://labelary.com/viewer.html) is able to use them ?

1. labelary is not an open source project (unless I'm mistaken?).
2. labelary doesn't appear to use Zebra fonts. The fixed width fonts are certainly not the same.

**Comment by yelhouti** [comment]
@primo-ppcg indeed labelary is not open source but the 0 font seems to be the same.
For fixed width not being the same is not a problem
