### ISSUE TITLE
Drawing Interleaved2of5 error when enable Mod10CheckDigit

### ISSUE THREAD

**Issue by ZhangYueqiu** [BinaryKits/BinaryKits.Zpl#205]
I get a error when drawing Interleaved2of5 code and enable Mod10CheckDigit, the error is "Data length invalid."
So I check the code in BarcodeLib:
![屏幕截图 2023-12-29 120121](https://github.com/BinaryKits/BinaryKits.Zpl/assets/16359818/28b97aad-9bbf-4071-8896-a1aea2932e3d)
And the draw code in this library:
![屏幕截图 2023-12-29 120718](https://github.com/BinaryKits/BinaryKits.Zpl/assets/16359818/31a73860-ab42-4831-8940-9ae5081f9193)
The link is:
https://github.com/BinaryKits/BinaryKits.Zpl/blob/8381d676916a820ac80cd819152b57acf63107e6/src/BinaryKits.Zpl.Viewer/ElementDrawers/Interleaved2of5BarcodeDrawer.cs#L48C62-L48C62

Is there need to use type Interleaved2of5_Mod10 when Mod10 is used?
`using var image = barcodeElement.Encode(TYPE.Interleaved2of5_Mod10 , barcode.Content);`

**Comment by primo-ppcg** [comment]
Likely.

I am still waiting patiently for the next release of [ZXing.Net](https://github.com/micjahn/ZXing.Net), after which I intend to remove the BarcodeLib dependency (#171), which would resolve this, and several other issues.

**Comment by ZhangYueqiu** [comment]
OK，Thank you for your reply.
