### ISSUE TITLE
Getting error on k8s but working fine on locally 

### ISSUE THREAD

**Issue by singh-coder23** [BinaryKits/BinaryKits.Zpl#209]
**Error Response** : 

Value cannot be null. (Parameter 'asset')    at SkiaSharp.HarfBuzz.BlobExtensions.ToHarfBuzzBlob(SKStreamAsset asset)

**Severatity** : Critical

**From** : 

var drawer = new ZplElementDrawer(printerStorage);
drawer.Draw(labelInfo.ZplElements)

Thanks & Regards,
Anand Singh(Coder)
India

**Comment by primo-ppcg** [comment]
Do you have an example label that produces the error?

**Comment by singh-coder23** [comment]
Thanks for your response @primo-ppcg. We have resolved the issue on prod as well. Due to some linux related font on k8s & docker nuget packages it was creating an issue.

**Comment by AMI3GOLtd** [comment]
> Thanks for your response @primo-ppcg. We have resolved the issue on prod as well. Due to some linux related font on k8s & docker nuget packages it was creating an issue.

What resolved your issue? We're experiencing the same...
