### ISSUE TITLE
UPS Maxicode viewing

### ISSUE THREAD

**Issue by johnvarney612** [BinaryKits/BinaryKits.Zpl#211]
Has anyone added the capability to view the UPS Maxicode? Any idea how to do that?

**Comment by primo-ppcg** [comment]
This is something I would definitely like to see. ZXing.NET does have a Maxicode decoder, but doesn't appear to have the corresponding encoder, so a bit of work would be required on that.

**Comment by johnvarney612** [comment]
![UPS with issues](https://github.com/BinaryKits/BinaryKits.Zpl/assets/121901810/f94bb692-d13a-40bf-8f28-0b9aa0c4c92a)
This shows the UPS label with Maxicode, incorrectly decoding "_F0" which should be "-" and barcode wrong size

**Comment by johnvarney612** [comment]
![UPS Labelary overlay](https://github.com/BinaryKits/BinaryKits.Zpl/assets/121901810/f505e89a-d8b1-4599-a502-863a344f9eed)
This shows the Labelary overlay with the "_F0" replaced with "-"

**Comment by johnvarney612** [comment]
![UPS Labelary](https://github.com/BinaryKits/BinaryKits.Zpl/assets/121901810/d2d3faf2-52aa-48fe-9d62-7a18a104c3a1)
This is the Labelary image

**Comment by primo-ppcg** [comment]
Resolved with #224.
