### ISSUE TITLE
Barcode issue(Priority)

### ISSUE THREAD

**Issue by singh-coder23** [BinaryKits/BinaryKits.Zpl#216]
Hi Guys,

Looks like binary kits are not supported 2D barcode(example : **PDF17 & Code 49**). Is that right or I misunderstood wrongly?

Please help us out for this. And are you guys planning to implement the above functionality in future?

Thanks & Regards,
Anand Singh(Coder)
India

**Comment by primo-ppcg** [comment]
PDF417 should not be difficult to add, code 49 on the other hand seems to be a bit more obscure.

**Comment by singh-coder23** [comment]
Can you tell the example for PDF417?

We are not able to convert into image through binary kits using pdf17.

**Comment by singh-coder23** [comment]
Hi @primo-ppcg,

On your official documents you guys have mentioned only these ANSI Codabar, Code 39, Code 128, EAN-13, Interleaved 2 of 5 supported for the barcode(https://github.com/BinaryKits/BinaryKits.Zpl).

Let's us know asap when you acknowledge my message.

Happy Coding

**Comment by primo-ppcg** [comment]
> We are not able to convert into image through binary kits using pdf17.

I'm almost certain you mean [^B7 - PDF417](https://support.zebra.com/cpws/docs/zpl/B7_Command.pdf) (pdf). It's widely used, and supported by most major libraries (including zxing).

> On your official documents you guys have mentioned only these ANSI Codabar, Code 39, Code 128, EAN-13, Interleaved 2 of 5 supported for the barcode

For 1D barcodes, I believe that list is correct.

**Comment by singh-coder23** [comment]
Hi @primo-ppcg ,

We have installed binary kits nuget package like below attached snapshot : 
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/20469915/e1902184-d7f4-4901-955a-5cc41244868b)
We are not able to draw 2D barcode using pdf417(in fact pdf417 haven't included into these nuget packages)

But when we are trying to download your source code from here(https://github.com/BinaryKits/BinaryKits.Zpl/tree/develop/src) it works as expected. Not sure why this inconsistancy exists?

@primo-ppcg lemme know if we can connect either on google meet or somewhere else virtually to look at this issue.

Thanks & Regards,
**Anand Singh(Coder)**

**Comment by Developer-Mukund** [comment]
Hi @primo-ppcg,

 We have compared the source code with nuget and got that Nuget does not have the method file to generate 2D barcode pdf417. Could you please provide update on this.
 
 Thanks much

**Comment by primo-ppcg** [comment]
The Nuget build is somewhat behind the development build. PDF417 is not supported in either.
