### ISSUE TITLE
ZPL Barcode issue (High Priority)

### ISSUE THREAD

**Issue by PradeepTiwari98** [BinaryKits/BinaryKits.Zpl#234]
When putting below zpl code in BinaryKit then not showing any barcode due to not set any field number (FN1 to FN4) values.

^XA
^BY5^FO60,1098^BCN,270,N,N,N,A^**FN1**^FS
^A0N,36,36^FO207,1383^CI0^**FN2**^FS
^FN1^**FDJVGTS0031660124034557**^FS
^FN2^**FDJVGTS0031660124034557**^FS
^BY5^FO480,705^BCN,270,N,N,N,A^**FN3**^FS
^A0N,36,36^FO630,983^CI0^**FN4**^FS
^FN3^**FD2LX2017**^FS
^FN4^**FD2LX2017**^FS
^XZ

But when replacing ^FN1 = **^FDJVGTS0031660124034557**, ^FN2 = **^FDJVGTS0031660124034557**,^FN3 = **^FD2LX2017** and ^FN4 = **^FD2LX2017** values then showing barcode, Please see below code and image

**ZPL Code**

^XA
^BY5^FO60,1098^BCN,270,N,N,N,A^FDJVGTS0031660124034557^FS
^A0N,36,36^FO207,1383^CI0^FDJVGTS0031660124034557^FS
^FN1^FS
^FN2^^FS
^BY5^FO480,705^BCN,270,N,N,N,A^FD2LX2017^FS
^A0N,36,36^FO630,983^CI0^FD2LX2017^FS
^FN3^^FS
^FN4^^FS
^XZ

**Image**
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/169337851/f86ab5e8-b3f4-48a5-b55e-d2dfa5d4ba3e)

**So, please confirm how to get barcode without replace field number values?**

**Comment by primo-ppcg** [comment]
Field Numbers are not applied to the current template. This is a bug. Minimal example:
```zpl
^XA
^BY3^FO60,60^BCN,100,Y,,,A^FN1^FS
^FN1^FDABC12345^FS
^XZ
```
