### ISSUE TITLE
Barcode render not correctly.

### ISSUE THREAD

**Issue by 1ua11** [BinaryKits/BinaryKits.Zpl#239]
Hello Guys, please help me. 
^XA 
^LH10,10
^LRY
^FO0105,155^GB690,20,53^FS 
^FO0150,155^BY3^BCN,53,N,N^FDABCDEF123456789^FS 
^XZ
That ZPL command above render OK with Labelary.
![1](https://github.com/BinaryKits/BinaryKits.Zpl/assets/24931238/75670beb-617f-4578-b0ec-04827a5d05ab)

But with BinaryKits.Zpl.Viewer (ver 1.2.0) not correct.
![2](https://github.com/BinaryKits/BinaryKits.Zpl/assets/24931238/eaa1886d-8bb6-4ae6-a6db-05f715515a3b)

**Comment by primo-ppcg** [comment]
Barcodes do not support reverse print. However, you can achieve the desired result by reverse printing the graphics box over the barcode:
```zpl
^XA
^LH10,10
^LRY
^FO0150,155^BY3^BCN,53,N,N^FDABCDEF123456789^FS
^FO0105,155^GB690,20,53^FS
^XZ
```
