### ISSUE TITLE
Issue: Right-Align Text Labels

### ISSUE THREAD

**Issue by KlausBenislavskis** [BinaryKits/BinaryKits.Zpl#245]
**Description:**
We need to align certain text labels to the right. We remember hearing about the Systems.Drawing replacement not supporting right text alignment directly. Can it be done with the new library?

**Current ZPL Code:**
```
^XA
^CF0,25,25
^FO805,716,1
^FDD-B2C^FS
^XZ

```
Expected 
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/72247119/b65fe266-086b-440e-804a-628ec593aa1a)
What we get gets rendered out of label
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/72247119/40cee30a-3abd-4e99-a51f-c9b794f8e29a)
We can modify the zpl code but would be nice if right alignment works

**Comment by primo-ppcg** [comment]
Justification parameter is missing for the following:
`^FO`
`^FT`
`^FW`

**Comment by KlausBenislavskis** [comment]
@primo-ppcg  Hey could we get a new version of the library released with this fix?
