### ISSUE TITLE
Library Fails to Render ZPL Code with Aztec Barcode and Text Fields

### ISSUE THREAD

**Issue by KlausBenislavskis** [BinaryKits/BinaryKits.Zpl#246]
**Description:**
We have encountered an issue where the current library fails to render specific ZPL code that includes an Aztec barcode and multiple text fields to an image. DPD labels return it.
Zpl code
```
^XA
^BOI,3,N,219,N,1,
^FH\^FD[)>\1E01\1D02\1D8020\1D40\1D327\1D05055004183043\1DGEOP\1D\1D150\1D12345678\1D001/001\1D3.45KG\1DN\1D123 Fake Street\1DFake City\1D\1D\1D\1E07\1DG03\1D0\1D0\1D1\1D\1F\1FJohn Doe\1F1234567890\1F1234567890\1F\1Fjohn.doe@fakeemail.com\1F\1F\1F\1DB\1D3.45KG\1DJohn Doe\1DFake Company\1D12345678\1D\1D\1D\1D\1D0\1D\1D\1E07\1DS010\1DFake Company\1F+1234567890\1FFake Company\1F\1F123 Fake Street\1F\1FFake City\1F12345\1F208\1D\1E\04^FS
^XZ
```
Expected:
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/72247119/3f6cd953-1199-45de-8223-9cc8fdd08bf1)
What we got: 
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/72247119/b5c967e5-ec1e-401c-a00e-582bfbf7072b)

**Comment by primo-ppcg** [comment]
You are correct, Aztec Code is not currently supported:
![image](https://github.com/BinaryKits/BinaryKits.Zpl/assets/4907320/2ae808e1-4714-4e53-ae6a-e527882e8125)

**Comment by KlausBenislavskis** [comment]
@primo-ppcg Any idea if this will get supported any time soon?

**Comment by primo-ppcg** [comment]
ZXing.NET supports Aztec Code, so It shouldn't be difficult to add. I'll spend some time on it this week.

**Comment by KlausBenislavskis** [comment]
Okay great to hear, Thanks!

**Comment by primo-ppcg** [comment]
@KlausBenislavskis please review #249

**Comment by KlausBenislavskis** [comment]
@primo-ppcg Cool thanks, can we get a package release to see how it looks?
