### ISSUE TITLE
Include the Labelary client in the main project?

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/BinaryKits.Zpl#26]
Follow discussion at:
https://github.com/BinaryKits/ZPLUtility/pull/24#issuecomment-869050657

@tinohager 
Please elaborate a bit. I assume the idea is to have a `ToLabelImage()` method on the engine?  This would be very convenient for testing or keeping a softcopy. 

Hope `System.Net.Http` do not have issue cross .Net framework to .Net core.

**Comment by tinohager** [comment]
I would have moved the current client. So everyone who needs it to generate a preview etc. could use it. At the moment we only have it in the test project. The dependency shouldn't be a problem I just didn't want to add any additional dependencies without asking. We can also move the client to a completely separate project.

**Comment by YipingRuan** [comment]
It absolutely helps during developing time.

I have some concerns if used in production. For example some client has strange network setup like proxy, then the `new HttpClient()` will not work. Should we consider intake an outside handler/factor? Or just keep plain and simple, leave those complex situations to the dev

**Comment by tinohager** [comment]
https://github.com/BinaryKits/BinaryKits.Zpl/pull/38
