### ISSUE TITLE
v2 => v3

### ISSUE THREAD

**Issue by tinohager** [BinaryKits/BinaryKits.Zpl#35]
Hi @YipingRuan 

From my point of view, we could release version 2. How does it look from your side?

**Comment by YipingRuan** [comment]
Great.

Do you think I should add a link to old document for 1.x users?
https://github.com/BinaryKits/ZPLUtility/blob/332e8544580492f414f03508d205fa192c7b67ce/README.md

**Comment by tinohager** [comment]
I think V1 has reached its age and it is time to update to V2. We have a V1 branch for users who are looking for the old documentation.

**Comment by tinohager** [comment]
Then, for example, the project would be called this in the future.

- BinaryKits.ZplUtility
- BinaryKits.ZplParser (alternative)
- BinaryKits.ZplLabel (alternative)
- BinaryKits.ZplElement (alternative)

![image](https://user-images.githubusercontent.com/8215186/125043472-41988780-e09b-11eb-8a12-b6d0b1d519a8.png)

**Comment by YipingRuan** [comment]
> I think V1 has reached its age and it is time to update to V2. We have a V1 branch for users who are looking for the old documentation.

https://www.nuget.org/packages/ZPLUtility/2.0.0

Looks okay?

**Comment by YipingRuan** [comment]
A bit confused about the naming, do you mean split the project to even smaller pieces or giving multiple alternative names?

**Comment by tinohager** [comment]
I would like to build another module for printing to which the ZPL code can be sent and I would outsource this to an extra project.

**Comment by tinohager** [comment]
Do you want to integrate the nuget push module into the ci/cd pipeline as well?

**Comment by YipingRuan** [comment]
> Do you want to integrate the nuget push module into the ci/cd pipeline as well?
If we are going to have frequent updates. I can try to do this later. :-P 


> I would like to build another module for printing to which the ZPL code can be sent and I would outsource this to an extra project.

Do you mean adding more projects to the solution, as siblings?

hmm, so the name should be 

- BinaryKits.ZplUtility.Engine
- BinaryKits.ZplUtility.Parser
- BinaryKits.ZplUtility.Element
?

**Comment by tinohager** [comment]
You can check this pipeline for the nuget publish step https://github.com/nager/Nager.Country/blob/master/.github/workflows/dotnet-core.yml

No my idea are other projects for other areas of application
BinaryKits.ZplLabel -> the current project
BinaryKits.ZplPrinter -> for printer logic, print label, get printer status
BinaryKits.ZplPreview -> labelary client

**Comment by YipingRuan** [comment]
Since they are all about Zpl, shouldn't we have used a common prefix like BinaryKits.Zpl, followed by [Label, Printer, Preview] ?

Added issue for the Nuget thing https://github.com/BinaryKits/ZPLUtility/issues/36

**Comment by tinohager** [comment]
So your suggestion would be `BinaryKits.Zpl.Label` or `BinaryKits.ZplLabel`?

**Comment by YipingRuan** [comment]
> So your suggestion would be `BinaryKits.Zpl.Label` or `BinaryKits.ZplLabel`?

Let's alight the possible plans. I am especially confused by "I would outsource this to an extra project", do you mean new Visual Studio project, new Visual Studio solution or GitHub repo.

Assuming we still keep under Binarykits (otherwise you can go Nager.ZplXXXXX freely), I prefer to group all ZPL things under BinaryKits.ZplUtility (like I may have other multiple items under BinaryKits.OfficeAutomation).

- Keep existing GitHub repo and Visual studio **solution** as they have the name "ZPLUtility"
- Split to different Visual studio **project** including [Label, Printer]

![image](https://user-images.githubusercontent.com/5492274/125383525-1d55e700-e3ca-11eb-828d-4d9771aa3462.png)

What do you think? Please feel free to fix the above as you are managing more repos.

**Comment by tinohager** [comment]
My suggestion is to rename the current Github project from `ZPLUtility` to `BinaryKits.Zpl`. When this happens via Github a redirect from the old url to the new one is automatically set up. The VisualStudio Solution would then be named like the project `BinaryKits.Zpl`. The current VisualStudio project would then be named `BinaryKits.Zpl`. If we integrate logic for printers then this Visual Studio project would be named `BinaryKits.Zpl.Printer` in the same Github project.

On nuget you can then reserve the prefix `BinaryKits.*` with it you get then a blue hook.

So actually very similar to your suggestion. With the nuget package the prefix I would find however very beautiful.

![image](https://user-images.githubusercontent.com/8215186/125411658-6acc5700-e3be-11eb-8546-b4aebf8aa701.png)

**Comment by YipingRuan** [comment]
Thank you for the above details and it looks great. 

I want to know more about what happens to the **nuget** part.

- Replace package ZPLUtility with BinaryKits.Zpl or BinaryKits.Zpl.Label? We can also just publish a new package
- How do users of current ZPLUtility upgrade, how to let them know?

**Comment by tinohager** [comment]
For me, both variants are okay. With `BinaryKits.Zpl.Label`, we might have a very clean structure.

On the old package name, we would simply release a new package again with a release note on the new package. Also we can mark the `ZPLEngine` method as obsolete with a comment there.
https://stackoverflow.com/questions/1759352/how-to-mark-a-method-as-obsolete-or-deprecated

**Comment by tinohager** [comment]
Yes, only the unit test project rename to BinaryKits.Zpl.Label.UnitTest, it is the test project of the label

**Comment by tinohager** [comment]
- https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices

> On nuget you can then reserve the prefix `BinaryKits.*` with it you get then a blue hook.
- https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

**Comment by YipingRuan** [comment]
I updated the v1 to note the obsolete, 
https://github.com/BinaryKits/BinaryKits.Zpl/commit/f8bb518fca11c84fcac142c487266b7c7d90c2ca

Will list to public after your check:
https://www.nuget.org/packages/ZPLUtility/1.6.0

If everything fine will follow the guide below and suggest users (if any?) to move:
https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

**Comment by tinohager** [comment]
I like the deprecate package.

**Comment by YipingRuan** [comment]
@tinohager 
Any more immediate changes needed?

**Comment by tinohager** [comment]
@YipingRuan  I do not think 😄

**Comment by tinohager** [comment]
can you maybe optimize the package description of the old package,

![image](https://user-images.githubusercontent.com/8215186/126277913-42538db6-3b42-4d19-9e90-e06027a7e5b7.png)

**Comment by YipingRuan** [comment]
Please suggest?

PS: the blue tick is done:
![image](https://user-images.githubusercontent.com/5492274/126281718-3167692d-94f6-4122-82dc-46ee125c8df2.png)

**Comment by tinohager** [comment]
i have add an example to the picture

**Comment by YipingRuan** [comment]
Let's try this:
![image](https://user-images.githubusercontent.com/5492274/126283326-fba56dc6-8584-4f2f-ba8b-cd70b08e08d2.png)
