### ISSUE TITLE
Add Nuget publish to Github Actions

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/BinaryKits.Zpl#36]

**Comment by tinohager** [comment]
```
  - name: Push NuGet package
      if: github.event_name != 'pull_request'
      run: |
        cd $GITHUB_WORKSPACE/out
        dotnet nuget push *.nupkg --source https://www.nuget.org/api/v2/package --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols true
```

**Comment by YipingRuan** [comment]
@tinohager 

No very sure about `--no-symbols` and version change detection.
Would you help on this Action update?


PS: I already added Repository secrets "NUGET_TOKEN"
![image](https://user-images.githubusercontent.com/5492274/125718513-f527edb1-74bb-4988-a7ec-e9eda8bb1421.png)

**Comment by tinohager** [comment]
maybe it works now without `--no-symbols`
https://github.com/NuGet/Home/issues/4864

**Comment by tinohager** [comment]
i have add the publish step
