### ISSUE TITLE
SkiaSharp on Linux and prepare docker

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/BinaryKits.Zpl#43]
To make the viewer work on Linux, seems we need to add the following to "BinaryKits.Zpl.Viewer.csproj" (tested)

````
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.3" />
````

https://github.com/mono/SkiaSharp/issues/1341

Otherwise:
![image](https://user-images.githubusercontent.com/5492274/128202982-c92b71ee-a8c7-4ef3-bc6e-2fe556c99079.png)

**Comment by tinohager** [comment]
I have fix this in my last commit https://github.com/tinohager/BinaryKits.Zpl/commit/e229d4d1afec2dc4e840aa779ad122c615cd49e6

**Comment by tinohager** [comment]
if you are open a `docker hub` account we can push an image with this github action
https://github.com/nager/Nager.Date/blob/master/.github/workflows/dockerimage.yml
