### ISSUE TITLE
BinaryKits.Zpl.Viewer status? 

### ISSUE THREAD

**Issue by samuelneff** [BinaryKits/BinaryKits.Zpl#44]
Hi! I was wondering what state `BinaryKits.Zpl.Viewer` is in; I saw it was being worked on pretty recently.

Does it render ZPL files now? 
How much of the ZPL language does it support? 
How much work is outstanding? 
Do you need help?

Thanks!

Sam

**Comment by YipingRuan** [comment]
Thank you. It does render a lot of things without using labelary.

A draft plan is here: https://github.com/BinaryKits/BinaryKits.Zpl/blob/2f08fe55dbf4afe25bcf011937a77b5f700511a1/src/BinaryKits.Zpl.Viewer/README.md

**Comment by tinohager** [comment]
@samuelneff Hi
We have only recently started the project but the rendering is already working very well as you can see in the image below.
![image](https://user-images.githubusercontent.com/8215186/128474677-e2654ce9-beca-411d-ba4d-65c4ff7d266c.png)


> Does it render ZPL files now?
Yes

> How much of the ZPL language does it support?
This is a difficult question because each command has many configuration parameters. I think the barcodes and the correct text rendering are the biggest issues at the moment.

> How much work is outstanding?
The current version is running. What exactly do you want to use the project for and what do you need?

> Do you need help?
Yes we are very glad about support, for example this is an open issue (https://stackoverflow.com/questions/68626710/skisharp-colormatrix-invert-black-white)

**Comment by tinohager** [comment]
Or an other issue `^XA^FO50,50^GB100,100,120,B,1^FS^XZ`

According to labelary it should look like this
![image](https://user-images.githubusercontent.com/8215186/128478428-9b336731-826c-4490-8b84-215035fe9440.png)

Our renderer generates this result
![image](https://user-images.githubusercontent.com/8215186/128478385-d21dbca8-9a42-41dd-b4ed-9c78e0ffb14a.png)

It would also be interesting to see the result on a real printer, best an original Zebra

**Comment by tinohager** [comment]
@samuelneff Do you have any feedback for us?

**Comment by samuelneff** [comment]
@tinohager Thank you for the detailed response. I can definitely help by rendering ZPL to a printer and sending you a picture of what was printed (not immediately, I had to loan out my printer to another dev, but I'll be getting another soon).

From the specifics of your example, it sounds like you're pretty far along if you're up to nitpicking about little things like rounded corners. That sounds great!

We're currently evaluating whether or not an offline license for labelary is feasible. If not, then this project is our next best option. We don't really need a viewer though; we need to convert to png. The concept is very similar so we assume we'll be able to adapt your viewer code to do the same thing, maybe with a little refactoring you would be ok with (i.e., moving logic to a dll for reuse, separate from the gui viewing code).

Best,

Sam

**Comment by YipingRuan** [comment]
@samuelneff In fact all the rendering is already in **BinaryKits.Zpl.Viewer as a dll**.  
https://www.nuget.org/packages/BinaryKits.Zpl.Viewer/
You may refer to the package and use like:
https://github.com/BinaryKits/BinaryKits.Zpl/blob/35e4c134e9f5c530331e6647ccfd6d3696308c69/src/BinaryKits.Zpl.Viewer.WebApi/Controllers/ViewerController.cs#L33


Out of curiosity, may I ask why the online labelary was not chosen? Client sensitive data or the warehouse do not have public internet access? Thanks!

**Comment by tinohager** [comment]
@samuelneff We have also a package for the viewer logic available via [nuget](https://www.nuget.org/packages/BinaryKits.Zpl.Viewer)

**Comment by tinohager** [comment]
@samuelneff i close this issue. If you have any further questions you are welcome to open an issue again.
