### ISSUE TITLE
Viewer - Website

### ISSUE THREAD

**Issue by tinohager** [BinaryKits/BinaryKits.Zpl#45]
It would be great if we could implement the viewer website in vue and remove the dependencies to external cdns.

Missing features on the current page
 - display if the result image is scaled (responsive change the size of the image)
 - render time
 - move test labels in a top menu
 - create a nice design for the website 😄

**Comment by YipingRuan** [comment]
If I understand correctly you already use `vue@next`? So you want to put the whole webpack thing?..

**Comment by tinohager** [comment]
Yes it is vue@next but not with `Single File Components` and i load some ressources from cdn. If the application run in a company network it is not sure you have internet access and then the page not work.

This is currently the full page
https://github.com/BinaryKits/BinaryKits.Zpl/blob/master/src/BinaryKits.Zpl.Viewer.WebApi/wwwroot/index.html

**Comment by tinohager** [comment]
I would like something in this direction, here i have a Frontend project that i copy after publish in the webapi project
https://github.com/nager/Nager.CertificateManagement

**Comment by YipingRuan** [comment]
Okay, great. 
I was wondering how you plan to blend the thing within an .net web project...

**Comment by danzk** [comment]
I'm not much help on the web, but I wouldn't mind implementing a Desktop viewer in WPF, if you are interested?

**Comment by tinohager** [comment]
@danzk You want to build a program in this direction but instead of WinForms based on WPF? Does the program have any other possibilities than displaying the preview? https://github.com/germanger/zpl-printer
