### ISSUE TITLE
Image not rendered correctly

### ISSUE THREAD

**Issue by stankojevtic** [BinaryKits/BinaryKits.Zpl#46]
Using code   
```
 IPrinterStorage printerStorage = new PrinterStorage();
 var analyzer = new ZplAnalyzer(printerStorage);
 var elements = analyzer.Analyze(zplCommands);

 var drawer = new ZplElementDrawer(printerStorage);
 var imageData = drawer.Draw(elements);
```
Image is not rendered correctly from ZPL commands. Using labelary viewer I checked that ZPL commands are correct. Rendered image is attached to this issue.

Any suggestions what could be wrong? 
![cbimage](https://user-images.githubusercontent.com/23387328/128505003-57b29073-9bdc-42ae-abbc-6a01bd0b7fe5.png)

**Comment by tinohager** [comment]
Please add zpl data of the label

**Comment by stankojevtic** [comment]
Zpl data:
^XA\r\n^MMT\r\n^LS0\r\n^FO0,0^GB3,1217,3^FS\r\n^FO809,0^GB3,1217,3^FS\r\n^FO0,0^GB809,3,3^FS\r\n^FO0,1215^GB809,3,3^FS\r\n^FO0,959^GB812,0,10^FS\r\n^FO0,1207^GB812,0,10^FS\r\n^FO492,965^GB0,253,10^FS\r\n^FT545,1123^A0N,90,91^FH\\^CI28^FDB-7^FS^CI27\r\n^FO0,690^GB812,0,10^FS\r\n^FO0,690^GB812,0,10^FS\r\n^FO0,177^GB812,0,2^FS\r\n^FO202,0^GB0,177,2^FS\r\n^FO0,0^GB202,178,100^FS\r\n^FO487,17^GB304,137,2^FS\r\n^FT494,55^A0N,35,38^FH\\^CI28^FDUS POSTAGE PAID^FS^CI27\r\n^FT494,99^A0N,35,38^FH\\^CI28^FDPTEST^FS^CI27\r\n^FT494,143^A0N,35,38^FH\\^CI28^FDEVS^FS^CI27\r\n^FT100,236^A0N,44,46^FH\\^CI28^FDUSPS PARCEL SELECT GROUND^FS^CI27\r\n^FO0,263^GB812,0,2^FS\r\n^FT230,752^A0N,38,37^FH\\^CI28^FDUSPS TRACKING #^FS^CI27\r\n^FT18,311^A0N,31,30^FH\\^CI28^FDJohn James^FS^CI27\r\n^FT18,350^A0N,31,30^FH\\^CI28^FDGOOGLE^FS^CI27\r\n^FT18,389^A0N,31,30^FH\\^CI28^FDSTE N^FS^CI27\r\n^FT18,428^A0N,31,30^FH\\^CI28^FD3695 CASCADE RD SW^FS^CI27\r\n^FT18,467^A0N,31,30^FH\\^CI28^FDATLANTA GA 30331-2146^FS^CI27\r\n^FPH,1^FT202,543^A0N,34,31^FH\\^CI28^FDJohn James^FS^CI27\r\n^FPH,1^FT202,586^A0N,34,31^FH\\^CI28^FDGOOGLE^FS^CI27\r\n^FPH,1^FT202,629^A0N,34,31^FH\\^CI28^FDPO BOX 3006 PO BOX 3006^FS^CI27\r\n^FPH,1^FT202,672^A0N,34,31^FH\\^CI28^FDTRENTON NJ 08619-0006^FS^CI27\r\n^FT68,611^A0N,34,33^FH\\^CI28^FDB099^FS^CI27\r\n^FO35,563^GB134,72,2^FS\r\n^FT100,1190^A0N,34,33^FH\\^CI28^FD2P 10000 00000 00044^FS^CI27\r\n^FPH,3^FT172,941^A0N,32,33^FH\\^CI28^FD9261 2123 4567 8900 0000 25^FS^CI27\r\n^FO8,775^GFA,12000,12000,100,P03FE1E00IF807IFC1E1IF0F8787IFE001FF0078I03C3FE1IF007803FFC1FE1IF0787FFC3FEI0FJ0783FC01FE0FF0JF83FC1FE00FF007F83FC01FE00FF07F803FC01IF00F87F803FE1IFI0F87FC003FFE0F0FF8,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::P03FE1E00IF807IFC1E1IF0F8787IFE001FF00F8I03C3FE1IF007803FFC1FE1IF0787FFC3FEI0FJ0783FC01FE0FF0JF83FC1FE00FF007F83FC01FE00FF07F803FC01IF00F87F803FE1IFI0F87FC003FFE0F0FF8,P03FE1E00IF807IFC1E1IF0F8787IFE001FF0078I03C3FE1IF007803FFC1FE1IF0787FFC3FEI0FJ0783FC01FE0FF0JF83FC1FE00FF007F83FC01FE00FF07F803FC01IF00F87F803FE1IFI0F87FC003FFE0F0FF8,\r\n^FO47,994^GFA,7150,7150,50,O07LFE1E1E3C007F878F001FEK038787K01EJ03FF878F0FFEK03LF0F001E1E03C0,:::::O07LFE1E1E3C007F878F001FEK03C78F8J01EJ03FF878F0FFEK03LF0F001E1E03C0,O07LFE1E1E3C007JF0E0E001FC003F87JFE0E1FFC03JF8F0F001FC003LF0F001E1E03C0,O07LFE1E1E3C007JF0F0E001FC003F87KF1E1FFC03JF8F0F001FE003LF0F001E1E03C0,:::::O07LFE1E1E3C007JF0F1F001FC003FC7KF1F3FFC03JF8E07003FE003LF0F001E1E03C0,O07LFE1E1E3C007F878F0JFEJ03FF8700F0KFC03F8787I0JFE003LF0F001E1E03C0,:::::O07LFE1E1E3C007F878F0JFEJ03FF8700F0KFC03F8787800JFE003LF0F001E1E03C0,O07LFE1E1E3C007IF8F01F1IFC003C78007I01EJ03F8787IF1JFC03LF0F001E1E03C0,O07LFE1E1E3C007IF8F00E1IFC00387800FI01EJ03F8787IF1JFC03LF0F001E1E03C0,:::::O07LFE1E1E3C007IF8F80E0IFC00387C00F8I0EJ03F8787FFE0JFC03LF0F001E1E03C0,O07LFE1E1E3C007F878IFI01EI0387KF0E01FC003F8787FFI01EI03LF0F001E1E03C0,O07LFE1E1E3C007F878IFI01CI0387KF0E01FC003F8787FFI01EI03LF0F001E1E03C0,::::O07LFE1E1E3C007F878IFI01CI03C7KF1E01FC003F8787FFI01EI03LF0F001E1E03C0,O07LFE1E1E3C007JF0F0FFCI0183FF8F8F0KFC003IF878IFEI01C3LF0F001E1E03C0,O07LFE1E1E3C007JF0F0FFEI03C3FF870F0KFC003IF870IFEI03C3LF0F001E1E03C0,:::::O07LFE1E1E3C007JF0F1FFCI07C3FF070F0KFC003IF078JFI01C3LF0F001E1E03C0,O07LFE1E1E3C007F8780FFE001IFC3F800FFI01E003C3C7807FF0FFEJ03LF0F001E1E03C0,::::::O07LFE1E1E3C007IF8701E0CK03FF00FF0FFE1CI03IF0780F1FK03LF0F001E1E03C0,O07LFE1E1E3C007IF8F00E1EK03FF80FF0FFE1EI03IF8700F1EK03LF0F001E1E03C0,:::::O07LFE1E1E3C007IF0F80F1EK03FF807E0FFE1EI03IF0780E1FK03LF0F001E1E03C0,O07LFE1E1E3C0078780FF0JFCI0387F8J01E1FFC03C7807F001JFC03LF0F001E1E03C0,:::::O07LFE1E1E3C0078780FF0JFEI0387F8J01E1FFC03C7807FI0JFC03LF0F001E1E03C0,O07LFE1E1E3C00787801IF03FFC003F8FFJ0E1EJ03C7800FE001FEI03LF0F001E1E03C0,O07LFE1E1E3C00787800FFE01FFC003F87FJ0E1EJ03C7800FF001FEI03LF0F001E1E03C0,:::::O07LFE1E1E3C007C7800FFE01FFC003F87FJ0E0CJ03C7800FFI0FEI03LF0F001E1E03C0,O07LFE1E1E3C007F8700FFE001EI03F8070IFJ01C03F8780IF001EI03LF0F001E1E03C0,O07LFE1E1E3C007F8780FFE001CI03F8070IFJ03C03F8780IF001EI03LF0F001E1E03C0,::::O07LFE1E1E3C007F8780FFE001EI03F8078IFJ03C03F8780IF001EI03LF0F001E1E03C0,O07LFE1E1E3C007F87801F00JF803C7IF1FJ0CI03C7800FF8JFC003LF0F001E1E03C0,O07LFE1E1E3C007F87800F01JFC0387IF0FI01EI03C7800FF0JFE003LF0F001E1E03C0,:::::O07LFE1E1E3C007F87800E01JFC03C7IF0FI01EI03C78007F0JFE003LF0F001E1E03C0,O07LFE1E1E3C007FF87J01E1FFC03IF80FF00E1FFC03C78I0FFI01FC03LF0F001E1E03C0,O07LFE1E1E3C007FF87J01E1FFC03IF80FF01E1FFC03C78I0FFI01FC03LF0F001E1E03C0,:::::O07LFE1E1E3C007IF8EI0E003E003C007F1F0KFC03IF07I0E001E003LF0F001E1E03C0,O07LFE1E1E3C007IF8F001E001C0038007F0F0KFC03IF87I0E001E003LF0F001E1E03C0,:::::O07LFE1E1E3C007IF8FI0E003C003C00FF8E0KFC03IF07001E003E003LF0F001E1E03C0,O07LFE1E1E3C007IF8FI01IFC3C3F87IFI01E3FC03C78J0FE1JFC3LF0F001E1E03C0,O07LFE1E1E3C007IF8FI01IFC3C3F87IFI01E1FC03C78J0FE1JFC3LF0F001E1E03C0,:::::O07LFE1E1E3C007FFC0F07E1IFC003C7IF8JFE03F83FF80707001FFE003LF0F001E1E03C0,O07LFE1E1E3C007FF80F0FE1IFC00387IF0JFE03FC3FF8070F001FFE003LF0F001E1E03C0,:::::O07LFE1E1E3C007FF8070FF1IFC003C7IF0JFE01FC3FF8070FI0FFC003LF0F001E1E03C0,O07LFE1E1E3C00787800IFEJ03C3FF8FFI01FFC03C3C7800IFEJ01C3LF0F001E1E03C0,O07LFE1E1E3C00787800IFEJ03C3FF87FI01FFE03C3C7800IFEJ03C3LF0F001E1E03C0,:::::O07LFE1E1E3C007CFC00IFEJ07C3FF8FF8I0FFE0183CFC007IFJ07C3LF0F001E1E03C0,O07LFE1E1E3C007KF00E1FFC3FC3F87JF001E1C003JF80F0IFE1FC3LF0F001E1E03C0,:::::O07LFE1E1E3C007KF00E1FFE3FC3F87JF001E1C003JF80F0IFE1FC3LF0F001E1E03C0,O07LFE1E1E3C007FF8FF0FI03FC003C00FF80FEJ01C3IF87F0F01FFE003LF0F001E1E03C0,O07LFE1E1E3C007FF87F0FI01FC0038007F00FEJ03C3IF87F0F01FFE003LF0F001E1E03C0,:::::O07LFE1E1E3C007FF87F0FI01FC0038007F00FEJ03C3IF87F0F01FFE003LF0F001E1C03C0,\r\n^PQ1,0,1,Y\r\n^XZ\r\n

**Comment by tinohager** [comment]
Do you test with the latest version?
![image](https://user-images.githubusercontent.com/8215186/128512796-19f4db07-9467-471e-84c8-86b1ab3ea656.png)

**Comment by stankojevtic** [comment]
Yes, I used source code that was active yesterday from BinaryKits.Zpl.Viewer. I see there were no changes in that project in last 2 days.

**Comment by tinohager** [comment]
Today we push an update

**Comment by stankojevtic** [comment]
Ok, cool. With the update image looks like the one you sent? If yes, regarding those small css fixes (e.g. US Postage Paid is out of the black box), is there any advice how we could fix them?

**Comment by tinohager** [comment]
No, for the correct text rendering we do not have a solution yet

**Comment by YipingRuan** [comment]
> Today we push an update

FYI, I set Action to publish the view web to https://binarykits-zpl-viewer.azurewebsites.net/

**Comment by tinohager** [comment]
@stankojevtic Are there any questions here?

**Comment by YipingRuan** [comment]
@tinohager  This seems not correct..
![image](https://user-images.githubusercontent.com/5492274/128883738-26baa9ff-269a-4556-a5a6-cae9b27e295d.png)

**Comment by tinohager** [comment]
I know this is the reason for this label example :) i think we are need a list for all open issues.
