### ISSUE TITLE
Usage of NetBarcode 2.0.0-beta.1

### ISSUE THREAD

**Issue by YipingRuan** [BinaryKits/BinaryKits.Zpl#49]
Need to fix when they got the 2.0 version ready.
https://github.com/Tagliatti/NetBarcode

Warning: /home/runner/.dotnet/sdk/5.0.302/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "NetBarcode [2.0.0-beta.1, )" or update the version field in the nuspec. [/home/runner/work/BinaryKits.Zpl/BinaryKits.Zpl/src/BinaryKits.Zpl.Viewer/BinaryKits.Zpl.Viewer.csproj]

**Comment by tinohager** [comment]
https://github.com/Tagliatti/NetBarcode

**Comment by tinohager** [comment]
https://github.com/Tagliatti/NetBarcode/issues/22
