### ISSUE TITLE
How can I use Zpl.Viewer in a .NET Framework App?

### ISSUE THREAD

**Issue by Outofnothing** [BinaryKits/BinaryKits.Zpl#66]
The nuget package BianryKits.Zpl.Viewer requires .NET Standard2.1, but event the latest .NET Framework doesn't support .NET Standard2.1 (see [this](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-platforms-support?WT.mc_id=DT-MVP-5002999)).
So, is there any way for me to use the Zpl.Viewer in a .NET Framework APP? Thanks in advance.

**Comment by tinohager** [comment]
I think that's certainly possible but you'd have to look at that in detail. Alternatively you can host the WebApi locally and simply send a webrequest from your application.

**Comment by Outofnothing** [comment]
> I think that's certainly possible but you'd have to look at that in detail. Alternatively you can host the WebApi locally and simply send a webrequest from your application.

Thanks. I created a Console App with .NET 5.0 and then call it in my .NET Framework App by Process.Start(). It's not elegant but it works.
