### ISSUE TITLE
QR Code Bar Code - Error correction

### ISSUE THREAD

**Issue by tinohager** [BinaryKits/BinaryKits.Zpl#67]
The ^BQ command has an `error correction` but also the ^FD command has an `error correction` (Page 114)
Does anyone make sense of the documentation?

**Comment by YipingRuan** [comment]
Seems the `error correction` decides

````
^XA
^FO20,20^BQ,2,10^FDQA,0123456789ABCD0123456789ABCD 2D code^FS

^FO400,20^BQ,2,10^FDHA,0123456789ABCD0123456789ABCD 2D code^FS

^FO20,400^BQH,2,10^FDLA,0123456789ABCD0123456789ABCD 2D code^FS

^FO400,400^BQL,2,10^FDHA,0123456789ABCD0123456789ABCD 2D code^FS

^XZ
````


![image](https://user-images.githubusercontent.com/5492274/131869560-728c11b3-bc31-4cb4-9817-7219e0f827ba.png)
