### ISSUE TITLE
Viewer - Chinese characters rendered by Zpl.Previewer not showing

### ISSUE THREAD

**Issue by Outofnothing** [BinaryKits/BinaryKits.Zpl#69]
When I try to preview a zpl label which contains some Chinese characters, the Chinese chars are not displayed properly, and they become some rectangels. See below:
![image](https://user-images.githubusercontent.com/33576247/131997531-3c1d1e34-cd56-48ba-bfa5-cd54c98b3ad7.png)

My ZPL code is:
`^XA^CI28
^CW1,E:SIMSUN.TTF
^FO20, 20^A1N,40, 30
^FD前片^FS
^XZ
`

**Comment by YipingRuan** [comment]
Need some font support

**Comment by Outofnothing** [comment]
> Need some font support

Could you please further your answer? What should I do to make it work? Thanks a lot.

**Comment by YipingRuan** [comment]
Currently we can't print Unicode/set font in the ZPL. (Anyway you need to upload the font to printer)


May I know where are you testing the render?

https://github.com/BinaryKits/BinaryKits.Zpl/blob/51d77ce9f9ffd7a1168d3a1a835d03c3184463b8/src/BinaryKits.Zpl.Viewer/ElementDrawers/TextFieldElementDrawer.cs#L47

if I change this line to:
`typeface = SKTypeface.FromFamilyName("Yu Gothic UI", SKFontStyleWeight.Bold, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);`

seems to be okay
![image](https://user-images.githubusercontent.com/5492274/132121734-0bf6f0d0-5fb7-4006-bc9a-d6b3de5f9f3e.png)

@tinohager 
Any possible to load font like ^CW1,E:SIMSUN.TTF?

**Comment by Outofnothing** [comment]
> Currently we can't print Unicode/set font in the ZPL. (Anyway you need to upload the font to printer)
> 
> May I know where are you testing the render? Your computer or web server?
> 
> https://github.com/BinaryKits/BinaryKits.Zpl/blob/51d77ce9f9ffd7a1168d3a1a835d03c3184463b8/src/BinaryKits.Zpl.Viewer/ElementDrawers/TextFieldElementDrawer.cs#L47
> 
> if I change this line to:
> `typeface = SKTypeface.FromFamilyName("SIMSUN", SKFontStyleWeight.Bold, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);`
> 
> seems to be okay
> ![image](https://user-images.githubusercontent.com/5492274/132121734-0bf6f0d0-5fb7-4006-bc9a-d6b3de5f9f3e.png)
> 
> @tinohager
> What's your plan to load font like ^CW1,E:SIMSUN.TTF? I can implement.

Thanks a lot. I use the Previewer in my computer (a .NET 5.0 Console App), here is my C# code:
```C#
private static void GeneratePreview(string zpl, double LabelWidth, double LabelHeight, int PrintDensityDpMM, string file)
        {
            IPrinterStorage printerStorage = new PrinterStorage();
            var drawer = new ZplElementDrawer(printerStorage);
            var analyzer = new ZplAnalyzer(printerStorage);
            var analyzeInfo = analyzer.Analyze(zpl);
            byte[] imageData = null;
            foreach (var labelInfo in analyzeInfo.LabelInfos)
            {
                imageData = drawer.Draw(labelInfo.ZplElements, labelWidth: LabelWidth, labelHeight: LabelHeight, printDensityDpmm: PrintDensityDpMM);
                File.WriteAllBytes(file, imageData);
            }
        }
```

I'm building my app using the nuget package Zpl.Previewer, if I would like the change line you mentioned, do I need to build the Zpl.Previewer by myself?

**Comment by YipingRuan** [comment]
Yes if you need immediate hardcoded font to fix this.

Or wait a while, eventually one of us will put the logic about taking`^CW1,E:SIMSUN.TTF`.

**Comment by Outofnothing** [comment]
> Yes if you need immediate hardcoded font to fix this.
> 
> Or wait a while, eventually one of us will put the logic about taking`^CW1,E:SIMSUN.TTF`.

Thanks very much. I guess I'll just wait until my boss pushes the progress.

**Comment by YipingRuan** [comment]
@Outofnothing 

Will you be able to test the commits at PR https://github.com/BinaryKits/BinaryKits.Zpl/pull/100  ?
