### ISSUE TITLE
Viewer - FB Command is not rendered correctly

### ISSUE THREAD

**Issue by Outofnothing** [BinaryKits/BinaryKits.Zpl#70]
The ZPL command FB (Field Block) command is not rendered correctly. I use the currently newest nuget package Zpl.Previewer 1.0.3.

The official [doc](https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf) says that:
>The ^FB command allows you to print text into a defined block type format.

The picture below ilustrate how FB affects the printed label. 
![image](https://user-images.githubusercontent.com/33576247/132182412-c7003e81-3423-4904-8f1e-1430d85b97c9.png)

In the Zpl.Previewer, however, the FB command won't affect the renderend image. It doesn't make difference whether I use the FB command or not.

**Comment by tinohager** [comment]
The viewer is still under development and is not a 100% preview. However, you are welcome to participate in improving it.

**Comment by ingfdoaguirre** [comment]
Hi, I made a PR solving this issue, I put images in the PR  #113
