### ISSUE TITLE
Publish docker image in dockerhub?

### ISSUE THREAD

**Issue by milankinen** [BinaryKits/BinaryKits.Zpl#80]
Hello and thanks for this awesome project! Our team has been searching for an offline ZPL viewer and this project looks like a great fit for our purposes. Do you have any plans to publish the viewer api as a docker image in [DockerHub](https://hub.docker.com) at some point? It should be pretty straightforward since you already provide a dockerfile in `src` folder to build the viewer api.

Cheers!

**Comment by tinohager** [comment]
Yes we have the plan, as soon as I find time again I will tackle the issue. If you use the project commercially we would be happy about a sponsorship.

**Comment by YipingRuan** [comment]
@tinohager not successful  https://github.com/BinaryKits/BinaryKits.Zpl/runs/3803410398?check_suite_focus=true 

:-(

**Comment by tinohager** [comment]
@YipingRuan try this as base https://github.com/nager/Nager.Date/blob/master/.github/workflows/dockerimage.yml

**Comment by tinohager** [comment]
@YipingRuan i check the build pipeline later

**Comment by YipingRuan** [comment]
> @YipingRuan i check the build pipeline later

At your time. You can also publish to your dockhub.

**Comment by tinohager** [comment]
A docker image is now available, maybe we still change the naming 
`docker run -p 80:80 yipingruan/binarykits-zpl`

**Comment by tinohager** [comment]
@YipingRuan Do you want to create an organization account?
https://hub.docker.com/orgs

**Comment by tinohager** [comment]
@milankinen a swagger is also available in the docker container
https://binarykits-zpl-viewer.azurewebsites.net/swagger/index.html

**Comment by YipingRuan** [comment]
@tinohager Can you confirm the docker hub is correct? (I may have deleted the wrong repo there)

https://hub.docker.com/repository/docker/yipingruan/binarykits-zpl

![image](https://user-images.githubusercontent.com/5492274/136305647-5c1d99aa-e954-4cfd-98da-a59b5ead080c.png)

**Comment by YipingRuan** [comment]
@tinohager Copied and added.
