### ISSUE TITLE
UPS ZPL fails to render

### ISSUE THREAD

**Issue by BrianLeishman** [BinaryKits/BinaryKits.Zpl#84]
I have ZPL labels that I get from UPS that render fine on Labelary (with some warnings), but seem to crash the viewer service

[test.zip](https://github.com/BinaryKits/BinaryKits.Zpl/files/7393296/test.zip)

**Comment by tinohager** [comment]
@YipingRuan this would have to be checked better in detail, but the exception could definitely be intercepted at this point.
