### ISSUE TITLE
Unsupported commands in Viewer

### ISSUE THREAD

**Issue by ankitfriends007** [BinaryKits/BinaryKits.Zpl#85]
Hi,
I'm trying to generate a label image with viewer but it renders incorrectly with the following error

![image](https://user-images.githubusercontent.com/5166523/140353723-deba1b9e-b91c-4206-bc1a-97a7e3e3e14f.png)

**Comment by tinohager** [comment]
this is not an error it informs you that these commands cannot be interpreted in our viewer.

**Comment by ankitfriends007** [comment]
Hi, yes but because of it, it is rendering it incorrectly, is there a possibility to add these or any short tutorial which i can read and add these?

**Comment by tinohager** [comment]
hi, this is the documentation of the zebra protocol https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf

- First we analyze the zpl code with the [CommandAnalyzers](https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer/CommandAnalyzers)
- after that we render the [ElementDrawers](https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer/ElementDrawers)
