### ISSUE TITLE
Datamatrix support

### ISSUE THREAD

**Issue by TheLarsinator** [BinaryKits/BinaryKits.Zpl#86]
Hi,

Are there any plans for supporting the ^BX command for creating data matrices?

-Lars

**Comment by tinohager** [comment]
hi, not at the moment

**Comment by Christian-Schou** [comment]
Would it be possible to do with a library like this: https://github.com/micjahn/ZXing.Net ? :)

**Comment by YipingRuan** [comment]
@tinohager 

Should we have a try?  If not ZXing.net we can also copy from DataMatrix.Net.

**Comment by tinohager** [comment]
At the moment I don't have time for new features. The viewer should also be changed to Zpl.Protocol. :/

**Comment by YipingRuan** [comment]
> At the moment I don't have time for new features. The viewer should also be changed to Zpl.Protocol. :/

I can try on the drawer part for now, are you okay to **include ZXing.net**?

**Comment by tinohager** [comment]
Of course

**Comment by Christian-Schou** [comment]
That is awesome work @YipingRuan! Thank you very much 👍 Is it available in the NuGet package as well?

**Comment by YipingRuan** [comment]
> That is awesome work @YipingRuan! Thank you very much 👍 Is it available in the NuGet package as well?

I think so, have a try https://www.nuget.org/packages/BinaryKits.Zpl.Viewer/1.0.6

Note only basic support.
