### ISSUE TITLE
Error in ZPL.Viewer

### ISSUE THREAD

**Issue by alejandro1990** [BinaryKits/BinaryKits.Zpl#89]
Hello,

I get the following error with the following zpl.

![image](https://user-images.githubusercontent.com/4300793/147576961-06b90010-99d1-43f3-b922-dfa16c58cd71.png)

The same thing happens with the {6} {7} {8} {9} ...
Can somebody help me?

**Comment by tinohager** [comment]
Have you try remove the line `^FH\^FD{00}{12}^FS` ?
