### ISSUE TITLE
Data matrix barcode issue

### ISSUE THREAD

**Issue by Christian-Schou** [BinaryKits/BinaryKits.Zpl#94]
Hi

I really like this project and I have built it into one of my APIs making labels. One of my services generating labels in ZPL are including QR codes. When the data is rendered using BinaryKits the QR code shows up as text, like if the library is not able to render the QR code into the image. When I copy and paste the exact same ZPL payload into Labelary I get the QR code showing up correctly. I tried changing the QR code from BXN to BQN and that generated the QR code, but the format and location inside the label was wrong. Because I get the data from a third-party provider I am not able to change BXN to BQN when data is generated.

My expectation was a QR code generated from this ZPL command:

`^FO70,214^BXN,4,200^FR^FDbarcode data here `

Can I do anything to get the QR code printed on the image?

**Comment by tinohager** [comment]
Sure the code is available here you just need to adjust the logic
https://github.com/BinaryKits/BinaryKits.Zpl/blob/master/src/BinaryKits.Zpl.Viewer/ElementDrawers/QrCodeElementDrawer.cs

Documentation
https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf

**Comment by Christian-Schou** [comment]
Hi @tinohager 

Thank you for the quick reply. After reading the documentation from your second link I can see that my data is actually not a QR code (sorry for confusion). It is a data matrix bar code. Is BinaryKits also capable of drawing these?

**Comment by Christian-Schou** [comment]
Found another issue with the same question. Closing it here. https://github.com/BinaryKits/BinaryKits.Zpl/issues/86
