### ISSUE TITLE
Text on labels is narrow after updating to latest version

### ISSUE THREAD

**Issue by Christian-Schou** [BinaryKits/BinaryKits.Zpl#98]
Hi 

After updating the NuGet package to the latest version the text height on the labels I draw using this library has become small. I tried reverting back to an older package and the labels looked good again in a matter of text height. Also, the barcode positions are a little bit off. The last barcode is rendered outside the label. I have tried generating a label on labelary.com to test if it was just the label that had some errors in the ZPL code. 

Below are two images, one from the render using BinaryKits and the other one is from labelary.com. Sorry, I had to blur the details - I know it makes it harder to see what I mean. Below is also a screenshot of the demo label I have made.

### Labelary.com
![Label generated using labelary](https://i.gyazo.com/98760671178ffeffe51eeff87cbeb010.png "Label generated using labelary" )

### BinaryKits.ZPL
![Label generated using BinaryKits](https://i.gyazo.com/ad0c141823db5b685ee012172437fb8c.png "Label generated using BinaryKits"){: width="250px"}.

### ZPL
`
^XA
^FT22,43
^A0N,,36
^FDEXPRESS WORLDWIDE^FS
^FT22,43
^A0N,,36
^FDEXPRESS WORLDWIDE^FS
^FT23,70
^A0N,,15
^FDDate and Company^FS
^FO386,0
^GB150,79,79,B^FS
^FT388,58
^A0N,,65
^FR^FDWPX^FS
^FO543,23
^IMR:dhllg1.GRF^FS
^FO0,78
^GB780,0,2,B^FS
^FT19,102
^A0N,,17
^FDFrom :^FS
^FT19,102
^A0N,,17
^FDFrom :^FS
^FT87,102
^A0N,,25
^FDCompany Name^FS
^FT87,129
^A0N,,25
^FDSender Name^FS
^FT87,156
^A0N,,25
^FDAddress1^FS
^FT87,182
^A0N,,25
^FDZip, City^FS
^FT87,209
^A0N,,25
^FDCountry^FS
^FT693,102
^A0N,,22
^FDOrigin:^FS
^FT694,140
^A0N,,41
^FDBLL^FS
^FT693,140
^A0N,,41
^FDBLL^FS
^FO0,220
^GB780,0,2,B^FS
^FT35,252
^A0N,,17
^FDTo :^FS
^FT35,252
^A0N,,17
^FDTo :^FS
^FO25,226
^GB2,31,5,B^FS
^FO28,224
^GB31,0,5,B^FS
^FO750,226
^GB2,31,5,B^FS
^FO720,224
^GB31,0,5,B^FS
^FO25,409
^GB2,31,5,B^FS
^FO28,439
^GB31,0,5,B^FS
^FO750,409
^GB2,31,5,B^FS
^FO720,439
^GB31,0,5,B^FS
^FT87,249
^A0N,,31
^FDReceiver Company^FS
^FT87,282
^A0N,,31
^FDReceiver Name^FS
^FT87,316
^A0N,,31
^FDAttention^FS
^FT87,349
^A0N,,31
^FDAddress1^FS
^FT87,390
^A0N,,40
^FDZip, City^FS
^FT87,390
^A0N,,40
^FD^FS
^FT87,434
^A0N,,40
^FDCountry^FS
^FT87,434
^A0N,,40
^FD^FS
^FT575,244
^A0N,,20
^FDContact:^FS
^FO0,448
^GB780,0,2,B^FS
^FT8,518
^A0N,,90
^FD.^FS
^FT204,510
^A0N,,58
^FDXX-XXX-XXX^FS
^FT203,510
^A0N,,58
^FDXX-XXX-XXX^FS
^FT744,518
^A0N,,90
^FD.^FS
^FO0,535
^GB780,0,2,B^FS
^FO0,535
^GFA,192,192,3,ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00ffff00000000^FS
^FO16,535
^GB551,63,63,B^FS
^FT19,581
^A0N,,48
^FR^FDC-RET^FS
^FT701,551
^A0N,,17
^FDTime^FS
^FT626,551
^A0N,,17
^FDDay^FS
^FO0,598
^GB780,0,2,B^FS
^FT12,656
^A0N,,25
^FDRef No: Some Reference No. Here^FS
^FT12,656
^A0N,,25
^FDRef No: Some Reference No. Here^FS
^FT524,615
^A0N,,17
^FDPce/Shpt Weight^FS
^FT700,615
^A0N,,17
^FDPiece^FS
^FT510,650
^A0N,,28
^FD1.0/39.0 kg^FS
^FT509,650
^A0N,,28
^FD1.0/39.0 kg^FS
^FT686,654
^A0N,,41
^FD1/2^FS
^FT686,654
^A0N,,41
^FD1/2^FS
^FT12,675
^A0N,,17
^FDContent : Demo content inside box^FS
^FO0,781
^GB780,0,2,B^FS
^FO39,802
^BY3,2.3,94
^B3N,N,94,N,N
^FD1111111111^FS
^FT165,917
^A0N,,26
^FDWAYBILL 11 1111 11 111^FS
^FO57,928
^BY3,2.7,205
^BCN,205,N,N,N,A
^FD2LBF:Country+123456789^FS
^FT222,1159
^A0N,,26
^FDCountry+123456789^FS
^FO0,1171
^GB780,0,2,B^FS
^FT12,1203
^A0N,,20
^FDRef Code:^FS
^FO123,1306
^BY3,3.0,205
^BCN,205,N,N,N,A
^FDPACKAGEIDHERE^FS
^FT202,1533
^A0N,,26
^FDPACKAGE ID HERE^FS
^XZ
`

#### Labelary.com
![Label generated using labelary](https://i.gyazo.com/cc6aa750ac3c5b6cea16d34be7d8f5ac.png "Label generated using labelary")

#### BinaryKits.ZPL
![Label generated using BinaryKits](https://i.gyazo.com/4afc8c9c13e5ef92b0ef244535610ead.png "Label generated using BinaryKits")

Hope you can help me clarify what is wrong. Can I replace anything inside the ZPL code before sending it to the drawer to make it better?

**Comment by YipingRuan** [comment]
Thanks for the feedback. Can you verify this issue only happens for BinaryKits.Zpl.Viewer 1.0.7,  and 1.0.6 is okay?

I may need to revert https://github.com/BinaryKits/BinaryKits.Zpl/pull/71

**Comment by Christian-Schou** [comment]
Yeah, the text is smaller than it should be and the text line height is larger than before. I just tested on 1.0.6 and that looks fine in terms of the text size and line-height. The barcodes are still a little off, but not like in the new version.

**Comment by YipingRuan** [comment]
try the 1.0.8

**Comment by Christian-Schou** [comment]
Hi @YipingRuan

Sorry for the late reply, have been very busy the last couple of days. I just tried upgrading to 1.0.8 and now get the following error: **Unable to allocate pixels for the bitmap**.

This is the ZPL without sensitive informations:
`~JO
^XA
^PMN
^MUD
^LH20,20
^PR6
^JMA
^CI27,146,198,157,216,143,197,145,230,155,248,134,229,132,228,142,196,148,246,153,214,129,252,154,220,130,233,144,201,241,164,165,209,164,241,162,243,160,225
^FO40,1045^FR^GB740,0,4^FS
^FO780,464^FR^GB0,585,4^FS
^FO620,462^FR^GB0,585,4^FS
^FO37,464^FR^GB0,585,4^FS
^FO40,918^FR^GB580,0,4^FS
^FO40,669^FR^GB580,0,4^FS
^FO37,459^FR^GB747,2,4^FS
^FO40,394^FR^GB744,2,4^FS
^FO40,169^FR^GB744,4,4^FS
^FO40,84^FR^GB744,4,4^FS
^FO40,1^FR^GB744,4,8^FS
^FO40,173^FR^GB28,4,9^FS
^FO218,173^FR^GB28,4,9^FS
^FO40,385^FR^GB28,4,9^FS
^FO218,385^FR^GB28,4,9^FS
^FO40,182^FR^GB14,4,9^FS
^FO232,182^FR^GB14,4,9^FS
^FO40,376^FR^GB14,4,9^FS
^FO232,376^FR^GB14,4,9^FS
^FO50,469^CI27^A0N,60,60^FR^FDPARCEL^FS
^FO50,514^CI27^A0N,20,20^FR^FD   ^FS
^FO70,214^BXN,4,200^FR^FDAtrackingCodeHere          OtherTrackingHere   LastTrackingHere                                            ^FS
^FO268,200^BY3,2.0,240^B2N,160,N,N,N^FR^FDIDHERE^FS
^FO335,367^CI27^A0N,26,26^FR^FDIDHERE^FS
^FO604,214^BXN,4,200^FR^FDA|CompanyName|City, Street, No|City||Order-Reference||                                ^FS
^FO40,409^CI27^A0N,50,30^FR^FDCtryCode^FS
^FO130,422^CI27^A0N,18,16^FR^FDdh^FS
^FO160,419^CI27^A0N,30,20^FR^FD09.03.2022^FS
^FO270,419^CI27^A0N,30,20^FR^FD08:02^FS
^FO330,404^CI27^A0N,60,40^FR^FD4.70^FS
^FO420,424^CI27^A0N,30,20^FR^FDkg^FS
^FO470,414^CI27^A0N,30,20^FR^FD1^FS
^FO500,414^CI27^A0N,30,20^FR^FD/^FS
^FO510,414^CI27^A0N,30,20^FR^FD1^FS
^FO580,414^CI27^A0N,30,20^FR^FDRTG^FS
^FO620,414^CI27^A0N,30,20^FR^FDIDHERE^FS
^FO45,14^CI27^A0N,83,96^FR^FDKBH^FS
^FO270,6^FR^GB70,78,40^FS
^FO280,14^CI27^A0N,83,98^FR^FD2^FS
^FO485,14^CI27^A0N,83,98^FR^FDDK^FS
^FO635,6^FR^GB150,78,40^FS
^FO615,14^CI27^A0N,83,98^FR^FDZIPHERE^FS
^FO50,94^CI27^A0N,83,67^FR^FDIDNOHERE^FS
^FO220,114^CI27^A0N,66,33^FR^FD2100^FS
^FO220,94^CI27^A0N,20,20^FR^^FDZipCode^FS
^FO370,94^CI27^A0N,20,20^FR^FDYour Track ID^FS
^FO370,139^CI27^A0N,30,30^FR^FDTRACKINGIDHERE^FS
^A0R,23,23^FO750,464^FVSender:^FS
^A0R,20,20^FO750,564^FVCustomer ID^FS
^A0R,20,20^FO750,684^FVIDHERE^FS
^A0R,20,20^FO750,814^FVContact ID^FS
^A0R,20,20^FO750,914^FVIDHERE^FS
^A0R,23,23^FO725,474^FVCompanyName^FS
^A0R,23,23^FO650,474^FVStreet                                    REF-NR:^FS
^A0R,23,23^FO625,474^FVDK^FS
^A0R,23,23^FO625,514^FVZIP^FS
^A0R,23,23^FO625,584^FVCity      Order-Ref^FS
^FO380,679^CI27^A0N,15,15^FR^FDCustomer number:^FS
^FO490,679^CI27^A0N,15,15^FR^FDNumberHere^FS
^FO50,714^CI27^A0N,30,22^FR^FDCustomerCompanyName^FS
^FO50,759^CI27^A0N,30,22^FR^FDCustomerAttention^FS
^FO50,829^CI27^A0N,30,22^FR^FDCity, Street^FS
^FO220,889^CI27^A0N,30,22^FR^FDCity ^FS
^FO50,889^CI27^A0N,28,20^FR^FDDK^FS
^FO110,889^CI27^A0N,28,20^FR^FD2100^FS
^FO725,442^CI27^A0N,18,16^FR^FDB2.00.0^FS
^FO50,924^CI27^A0N,20,20^FR^FDContact^FS
^FO50,949^CI27^A0N,20,20^FR^FDPhone^FS
^FO120,949^CI27^A0N,20,20^FR^FD^FS
^FO50,974^CI27^A0N,20,20^FR^FDNote^FS
^FO150,974^CI27^A0N,20,20^FR^FDNOTE^FS
^FO50,999^CI27^A0N,20,20^FR^FDNote^FS
^FO20,1112^GFA,09216,09216,00096,
^FO45,1327^ADN,10,20^FR^FD^FS
FF,00,00,
^PQ1
^XZ
`

When drawing the same label on labelary I get the following result. The text is a little messed up, but that's because I removed all tracking and customer data with some placeholders.
!["Label"](https://i.gyazo.com/88729cafae554818ee22c696f19a3af0.png)

Please let me know if I can do anything :)

**Comment by tinohager** [comment]
@Christian-Schou please check your label at which command the error occurs this can be done easily by removing statement blocks when you have determined at which statement block the error occurs a detailed analysis can be done

**Comment by Christian-Schou** [comment]
Hi @tinohager 

When I remove this line: `^FO268,200^BY3,2.0,240^B2N,160,N,N,N^FR^FDIDHERE^FS`

The label is able to be rendered, the datamatrix sizes are not correct, but my guess is that the "style" is applied from that line? But it can render the label.

~JO ^XA ^PMN ^MUD ^LH20,20 ^PR6 ^JMA ^CI27,146,198,157,216,143,197,145,230,155,248,134,229,132,228,142,196,148,246,153,214,129,252,154,220,130,233,144,201,241,164,165,209,164,241,162,243,160,225 ^FO40,1045^FR^GB740,0,4^FS ^FO780,464^FR^GB0,585,4^FS ^FO620,462^FR^GB0,585,4^FS ^FO37,464^FR^GB0,585,4^FS ^FO40,918^FR^GB580,0,4^FS ^FO40,669^FR^GB580,0,4^FS ^FO37,459^FR^GB747,2,4^FS ^FO40,394^FR^GB744,2,4^FS ^FO40,169^FR^GB744,4,4^FS ^FO40,84^FR^GB744,4,4^FS ^FO40,1^FR^GB744,4,8^FS ^FO40,173^FR^GB28,4,9^FS ^FO218,173^FR^GB28,4,9^FS ^FO40,385^FR^GB28,4,9^FS ^FO218,385^FR^GB28,4,9^FS ^FO40,182^FR^GB14,4,9^FS ^FO232,182^FR^GB14,4,9^FS ^FO40,376^FR^GB14,4,9^FS ^FO232,376^FR^GB14,4,9^FS ^FO50,469^CI27^A0N,60,60^FR^FDPARCEL^FS ^FO50,514^CI27^A0N,20,20^FR^FD ^FS
 ^FO70,214^BXN,4,200^FR^FDAtrackingCodeHere OtherTrackingHere LastTrackingHere ^FS 

**_^FO268,200^BY3,2.0,240^B2N,160,N,N,N^FR^FDIDHERE^FS_** <-- Troublemaker

^FO335,367^CI27^A0N,26,26^FR^FDIDHERE^FS
 ^FO604,214^BXN,4,200^FR^FDA|CompanyName|City, Street, No|City||Order-Reference|| ^FS 
^FO40,409^CI27^A0N,50,30^FR^FDCtryCode^FS ^FO130,422^CI27^A0N,18,16^FR^FDdh^FS ^FO160,419^CI27^A0N,30,20^FR^FD09.03.2022^FS ^FO270,419^CI27^A0N,30,20^FR^FD08:02^FS ^FO330,404^CI27^A0N,60,40^FR^FD4.70^FS ^FO420,424^CI27^A0N,30,20^FR^FDkg^FS ^FO470,414^CI27^A0N,30,20^FR^FD1^FS ^FO500,414^CI27^A0N,30,20^FR^FD/^FS ^FO510,414^CI27^A0N,30,20^FR^FD1^FS ^FO580,414^CI27^A0N,30,20^FR^FDRTG^FS ^FO620,414^CI27^A0N,30,20^FR^FDIDHERE^FS ^FO45,14^CI27^A0N,83,96^FR^FDKBH^FS ^FO270,6^FR^GB70,78,40^FS ^FO280,14^CI27^A0N,83,98^FR^FD2^FS ^FO485,14^CI27^A0N,83,98^FR^FDDK^FS ^FO635,6^FR^GB150,78,40^FS ^FO615,14^CI27^A0N,83,98^FR^FDZIPHERE^FS ^FO50,94^CI27^A0N,83,67^FR^FDIDNOHERE^FS ^FO220,114^CI27^A0N,66,33^FR^FD2100^FS ^FO220,94^CI27^A0N,20,20^FR^^FDZipCode^FS ^FO370,94^CI27^A0N,20,20^FR^FDYour Track ID^FS ^FO370,139^CI27^A0N,30,30^FR^FDTRACKINGIDHERE^FS ^A0R,23,23^FO750,464^FVSender:^FS ^A0R,20,20^FO750,564^FVCustomer ID^FS ^A0R,20,20^FO750,684^FVIDHERE^FS ^A0R,20,20^FO750,814^FVContact ID^FS ^A0R,20,20^FO750,914^FVIDHERE^FS ^A0R,23,23^FO725,474^FVCompanyName^FS ^A0R,23,23^FO650,474^FVStreet REF-NR:^FS ^A0R,23,23^FO625,474^FVDK^FS ^A0R,23,23^FO625,514^FVZIP^FS ^A0R,23,23^FO625,584^FVCity Order-Ref^FS ^FO380,679^CI27^A0N,15,15^FR^FDCustomer number:^FS ^FO490,679^CI27^A0N,15,15^FR^FDNumberHere^FS ^FO50,714^CI27^A0N,30,22^FR^FDCustomerCompanyName^FS ^FO50,759^CI27^A0N,30,22^FR^FDCustomerAttention^FS ^FO50,829^CI27^A0N,30,22^FR^FDCity, Street^FS ^FO220,889^CI27^A0N,30,22^FR^FDCity ^FS ^FO50,889^CI27^A0N,28,20^FR^FDDK^FS ^FO110,889^CI27^A0N,28,20^FR^FD2100^FS ^FO725,442^CI27^A0N,18,16^FR^FDB2.00.0^FS ^FO50,924^CI27^A0N,20,20^FR^FDContact^FS ^FO50,949^CI27^A0N,20,20^FR^FDPhone^FS ^FO120,949^CI27^A0N,20,20^FR^FD^FS ^FO50,974^CI27^A0N,20,20^FR^FDNote^FS ^FO150,974^CI27^A0N,20,20^FR^FDNOTE^FS ^FO50,999^CI27^A0N,20,20^FR^FDNote^FS ^FO20,1112^GFA,09216,09216,00096, ^FO45,1327^ADN,10,20^FR^FD^FS FF,00,00, ^PQ1 ^XZ

**Comment by YipingRuan** [comment]
@Christian-Schou

At the moment I can't make the Data Matrix totally correct, Just draw there for placeholder (It can be scanned correctly).  Or you tell me how to deal the Error redundancy thing with ZXing.net.
